### ISSUE TITLE
Mac compatibility (10.6.8)

### ISSUE THREAD

**Issue by olliephillips** [espruino/EspruinoWebIDE#100]
Several issues encountered with Mac version 10.6.8. Installed via Chrome store then install latest from Github repo, same results.

Issues:
No terminal cursor - could not key.
Code not push default LED code to board, no errors, appeared to complete, but nothing running on the board
Could not flash the board using the built in facility (basic or advanced)

Gordon replicated 21/07/14.
Forum link:- http://forum.espruino.com/conversations/1747/

Low priority nice to have.

**Comment by gfwilliams** [comment]
Closing now - I think a USB firmware update did make this a little better
