### ISSUE TITLE
NPM support is not overridden by standard Espruino modules

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoWebIDE#106]
For instance `require('clock')` should load Espruino's clock - not node's.

**Comment by programmicha** [comment]
is it possible to add some form of error notification for the user?
right now the IDE just does nothing, but showing
```
NPM: Checking NPM at http://registry.npmjs.org/Font8x16
ERROR: Not Found
```
in console

**Comment by gfwilliams** [comment]
NPM support is now dead, closing this
