### ISSUE TITLE
WebIDE doesn't wait for reset to finish after sending reset(), before sending code

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/EspruinoWebIDE#110]
I've been noticing this recently. Not sure if it's new, or my Desk Lamp is busier than it used to be. 

If you have an Espruino that's been doing stuff, ie, not freshly reset, reset() can take a second or two to actually reset. 

However, the WebIDE doesn't seem to be aware of this, and just starts flinging code at it while it's resetting. This, unsurprisingly, results in the Espruino not receiving the code.   This reproduces like clockwork on my Desklight - every single time, if I've run onInit() and it's been doing stuff, even if it's fully responsive at the time, it doesn't reset in time to catch all the code being sent. The workaround is to reset() manually before sending code - then the reset happens quickly, and the code sends fine. The WebIDE should ideally wait for the Espruino to indicate successful reset before starting to send code, but failing that, a simple delay could prevent the problem from manifesting.

**Comment by gfwilliams** [comment]
Fixed - doesn't wait for a response, but does wait ~250ms.
