### ISSUE TITLE
Minifier error message refers to IE8 browser

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/EspruinoWebIDE#114]
Input_0:129: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option

I reckon this shouldn't appear ;-)

**Comment by gfwilliams** [comment]
Is that with the online closure compiler minifier, or the built-in one?

I'm not sure if we can disable it when online (and I have no bloody clue why it should be an error), but hopefully we can disable it offline at least.

**Comment by SpenceKonde** [comment]
Online closure compiler. Can we pass that language_in option. 

I just realized that the new minification isn't enabled by default - mistook the expanded info from minification for the offline minification being used by default. I'll definitely start using the offline minification and see how that behaves.

**Comment by gfwilliams** [comment]
Closing - haven't seen this occur for a while - I think I changed the minifier args which helped with this
