### ISSUE TITLE
Can't load AT module from sandbox

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/EspruinoWebIDE#116]
While trying to investigate this issue http://forum.espruino.com/conversations/266416/ I decided I wanted to verify that _any_ line handlers were being called. So I saved AT.js, modified it to uncomment those lines, and put it in my espruino sandbox modules directory. 

Now, when I try to send, an extra message regarding minification shows up, but the AT module is not sent to the Espruino, so the first time it tried to communicate with the ESP8266 it barfs:

```

ERROR: SD card must be setup with E.connectSDCard first
WARNING: Module "AT" not found
=undefined
Uncaught Error: Field or method "connect" does not already exist, and can't create it on undefined
 at line 1 col 22
{h.at=d=require("AT").connect(a);require("NetworkJS").create...
                      ^

```

Removing the AT module from the espruino sandbox, and restarting the IDE restores normal functionality. But it is still impossible to do work on the AT module on your local machine! 

:-(

**Comment by gfwilliams** [comment]
Hmm - thanks!

I bet this happens to any module referenced from another module that's in the sandbox. Usually some effort goes into handling these recursive requires, but I bet that doesn't happen in the case of the sandbox stuff!

A quick hack would be to put `require("AT")` in the head of the editor window of the Web IDE.

**Comment by gfwilliams** [comment]
Fixed this a while back - it was a regression in project.js
