### ISSUE TITLE
Web IDE has no border when loaded as a Google App

### ISSUE THREAD

**Issue by nkolban** [espruino/EspruinoWebIDE#117]
When I use the Web IDE on Windows 10 launched as a Google App, the resulting window has no borders which causes it to look wrong when there is a white background app in the background of the screen.  See the attached screen shot as an example.

<img width="504" alt="2015-08-28_16-08-51" src="https://cloud.githubusercontent.com/assets/3421732/9557177/7380b410-4d9f-11e5-96c0-b72879a5274f.png">

**Comment by gfwilliams** [comment]
Yes, that is a bit frustrating. I guess maybe the scrollbar could always be shown, which would give a clearer edge.

However it's not a big issue for many people as it probably overlaps the background of a non-white window.

**Comment by gfwilliams** [comment]
Closing this, and nobody else seems bothered about it.
