### ISSUE TITLE
Local minified modules

### ISSUE THREAD

**Issue by olliephillips** [espruino/EspruinoWebIDE#122]
Noticed that when I try to upload a local module that is already minified, the IDE remarks that the code cannot be minified further, but it seems to hang the upload process -  the code upload does not complete.

**Comment by gfwilliams** [comment]
Interesting - thanks! Probably not too big an issue to change that...

**Comment by wilberforce** [comment]
I have found a work around hack - just add some spaces and new lines to the minified file, and save.

Then the minifier has some work to do, and then continues!

**Comment by gfwilliams** [comment]
Thanks for letting us know. It's a shame I missed this bug when I did the latest Web IDE update :(

**Comment by gfwilliams** [comment]
Fixed with https://github.com/espruino/EspruinoTools/commit/27bbc286e292b97e9c53f727f57a3b0b03e5af69
