### ISSUE TITLE
Project dialog wont show when folder icon clicked if a file with no extension in  'modules' or 'binary' folders.

### ISSUE THREAD

**Issue by dmcnaugh** [espruino/EspruinoWebIDE#124]
The Project dialog wont show when the folder icon is clicked if any file without an extension exists in either the  `modules` or `binary` folders.

Once the offending file(s) is removed then the Project dialog will appear when the folder icon is clicked.

This had me wondering if the project functionality existed at all until I started looking at the source.

**Comment by gfwilliams** [comment]
Thanks - that's a strange one. I'd guess there's probably some kind of error shown on the console - shouldn't be a hard one to fix.
