### ISSUE TITLE
try to use multiple ips  

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#126]
in serial_socket.js is explained how to set more than one IP

cant get this working

Settings:
![bildschirmfoto 2016-01-28 um 18 49 20](https://cloud.githubusercontent.com/assets/15932646/12653450/e99cf28a-c5ef-11e5-8e2f-fe8ce5ba77c1.JPG)

Connect:
![bildschirmfoto 2016-01-28 um 18 50 18](https://cloud.githubusercontent.com/assets/15932646/12653473/04e36e5c-c5f0-11e5-830c-5d597732e14f.JPG)

```
  function init() {
    Espruino.Core.Config.add("SERIAL_TCPIP", {
      section : "Communications",
      name : "Connect over TCP Address",
      description : "When connecting, add a menu item to connect to a given TCP/IP address (eg. `192.168.1.2` or `192.168.1.2:23`). Leave blank to disable. Separate multiple ip addressess with a semi-colon",
      type : "string",
      defaultValue : "", 
    });
  }  
```

**Comment by MaBecker** [comment]
this has to be fixed in EspruinoTools"

**Comment by gfwilliams** [comment]
Fixed anyway
