### ISSUE TITLE
dead keys on console

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#129]
did some tests with the version 0v60 of WebIDE

found some dead chars/keys working on console:   ^  `   ´  ~

those chars/keys work fine in the editor

not sure if this is a WebIDE or a firmware issue
tested on 1v84.tve_master_f35ac96

**Comment by gfwilliams** [comment]
I don't see this on the new Web IDE with a Pico... Maybe someone else could confirm?

Could you also try on a firmware that you're sure worked fine before?

If I'm honest I'm struggling to think of any changes that could have caused this kind of problem - are you sure it's not just your PC?

**Comment by MaBecker** [comment]
running on MAC OS, will try now on Windows

**Comment by HyGy** [comment]
I'ts working here under ubuntu linux.

**Comment by MaBecker** [comment]
ok - on Windows it works ! 

there is something spezial using Mac OS X

**Comment by olliephillips** [comment]
I have tried with a Pico and fine - though I can't find one of the keys to test, on my Macbook (´). All rest of fine in both console and editor

**Comment by gfwilliams** [comment]
Closing this as it seems fine for everyone else. I've tried on max,windows and linux and it seems fine

**Comment by MaBecker** [comment]
yes now it works fine with WebIDE 0.65.1,  ESPs and Mac OS X
