### ISSUE TITLE
module not found ...

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#130]
the WebIDE show "Module <name> not found"  for build in modules 

![Wifi and ESP8266](https://cloud.githubusercontent.com/assets/15932646/13499489/f671aade-e15e-11e5-8771-33573c8c8349.JPG)

**Comment by gfwilliams** [comment]
Which device, and any example code?

It usually happens when the JSON file for a device is wrong or can't be downloaded

**Comment by MaBecker** [comment]
my internet connection is very unstable at the moment (on train)

device: ESP8266 
sample code:

`````
var esp = require("ESP8266");
var wifi = require("Wifi");
````

**Comment by gfwilliams** [comment]
If you look at the console (under settings now) you might find it shows an error loading the JSON file when you connected? If you disconnect and reconnect when you have a network connection you might find the warning goes away.

**Comment by MaBecker** [comment]
Ok, I understand thanks
