### ISSUE TITLE
Service Worker support

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoWebIDE#143]
It'd allow the Web IDE website to work offline (this wouldn't affect the  actual Chrome Web App version)

**Comment by jrstanley** [comment]
Can I ask why the Service Worker was disabled in 9a2b33119b717ce0d65e5dcc0fbd4f856882fdbc? If there were issues, I'd like to offer to take a look into them.

**Comment by gfwilliams** [comment]
Yes, at the moment it's buggy and I haven't had time to fix it.

Basically when it was enabled it totally broke the site and a normal reload wouldn't fix it so the commit really messed up some people that were using https://espruino.github.io/EspruinoWebIDE/. I wanted to make sure I didn't repeat that.

If you'd be willing to take a look at it, that'd be great!
