### ISSUE TITLE
Chrome App Migration?

### ISSUE THREAD

**Issue by bgiesing** [espruino/EspruinoWebIDE#144]
In case you haven't seen yet @gfwilliams, Google is discontinuing Chrome apps on every platform except Chrome OS. Any plans for this? Google says devs should convert it to either Progressive Web Apps or native packaging with Electron/NW.js (which you do the later and issue #143 is apart of the former)

https://developers.chrome.com/apps/migration

**Comment by gfwilliams** [comment]
Thanks for the update - yes, sadly I have seen it. They've totally screwed Espruino users over.

Unfortunately I need access to USB Serial devices, and Web USB doesn't appear to allow this. I've filed a bug here that'd be good to get some noise around: https://github.com/WICG/webusb/issues/56

If it works, it would be pretty cool - negating the need to a Web App at all. However I'm not inclined to put much effort into that unless Google decide to kill it too.

So while Service workers would be cool (and might be added for Puck.js and Web Bluetooth), they won't actually help here unless Web USB changes to allow other devices to work with it. Quite a few users use the filesystem support too, and there's no way to get that working for them under a non-web-app system unless I write plugins (and again, I'm not inclined to spend much time on a Chrome-specific plugin unless Google kill that later on as well).

A while back I got a bit scared by the total lack of effort going into the Chrome Serial API, so I decided to come up with a plan B. As such there is an Electron-based version of the Web IDE now: `npm install espruino-web-ide`

So it's not the end of the world. It's still not great though - I'll need to create and keep up to date installer packages for Windows and Mac, which is way more effort for me (effort which should be spent making Espruino better). It also sucks for users, as it's now definitely not a one-click install (and will cause problems for the Schools using Espruino)

**Comment by gfwilliams** [comment]
Update on this - Chrome app support officially ends June 2020 now: https://chromeunboxed.com/google-announces-timeline-for-the-end-of-chrome-apps-on-chromebooks/

Web Serial support has now been added (by Reilly Grant at Google!) so actually we're good to go with http://espruino.com/ide

Also there is an NW.js port as well, which is available from http://www.espruino.com/Web+IDE

**Comment by thyttan** [comment]
I tried ["Installing from GitHub (Latest Version)" -> "Running in Chrome"](https://github.com/espruino/EspruinoWebIDE#running-in-chrome)

Which rendered this in the browser:
![image](https://github.com/espruino/EspruinoWebIDE/assets/97237430/ed6d28fc-4a76-495d-abe5-d96eebeb99bd)

This was tested running on Fedora Linux 38, kernel Linux 6.4.4-200.fc38.x86_64, Cromium web browser 114.0.5735.198.

I suggest ripping this "Running in Chrome" section out, or adding a disclaimer at the top of it.

**Comment by gfwilliams** [comment]
Thanks - just updated the readme
