### ISSUE TITLE
Board Information: Exports displays incorrectly

### ISSUE THREAD

**Issue by wardy** [espruino/EspruinoWebIDE#146]
Exports under board information displays as ```[object Object]```

<img width="1025" alt="screen shot 2016-10-05 at 11 49 29" src="https://cloud.githubusercontent.com/assets/13730223/19110432/cf3f7ddc-8af1-11e6-97aa-247103537d39.png">

**Comment by gfwilliams** [comment]
thanks - just fixed :)
