### ISSUE TITLE
missing syntax hints

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#151]
I am missing the syntax error hints next to the line numbers.

Is this a config setting I am missing ?

**Comment by gfwilliams** [comment]
Wow, no - thanks! Yes, that's a bug. Can't believe we didn't notice that!

**Comment by gfwilliams** [comment]
Fixed with c18bb524d21cce6580e6ffd0511e397df4a3d8eb - I updated CodeMirror so I want to check it's not broken before doing a release. If you want to check it out you can try the version on GitHub though
