### ISSUE TITLE
Retina display icons

### ISSUE THREAD

**Issue by beaufortfrancois** [espruino/EspruinoWebIDE#155]
It would be nice to have a retina version for `img/icons.png`.
Is that something @gfwilliams can generate easily?

**Comment by gfwilliams** [comment]
Closing as not that easy, and seems there's not much interest.

Is someone did want to look at this, `extras/make_icons.sh` contains code to make the icon file, but we're reliant on low-res versions of the first few icons. I guess worst case these could just be traced back into SVG using inkscape
