### ISSUE TITLE
Flasher URL is invalid in Espruino Web IDE

### ISSUE THREAD

**Issue by Alaneor** [espruino/EspruinoWebIDE#156]
Hello,

The web IDE's flasher is currently broken - clicking on the link in the Settings menu, it does an XHR request to www.espruino.com/data/settings_flasher.html. However, the correct link seems to be www.espruino.com/ide/data/settings_flasher.html .

**Comment by gfwilliams** [comment]
Ahh - thanks! Flashing only works for USB-connected Espruino devices at the moment so I admit I didn't test that. I'll try and get that fixed, and hopefully Web Bluetooth flashing will get added soon.

**Comment by Alaneor** [comment]
Awesome, thank you for your help!
