### ISSUE TITLE
Serial ports don't show up nicely if port description is too long

### ISSUE THREAD

**Issue by yerpj** [espruino/EspruinoWebIDE#160]
```
COM3
Intel(R) Active Management Technology - SOL
```

When displaying this COM port, text is truncated because of the last line effectively prints on two lines, thus shifting `COM3` out of the window.
I found as a workaround to reduce the font-size of the port description [in the CSS](https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/css/components.css#L312) :
```css
font-size: 40%; /* instead of 70% */
```

Maybe a better solution would be to truncate the port description if longer than 30 characters...

**Comment by gfwilliams** [comment]
Fixed - thought i'd do it so it wouldn't break even if text was really long
