### ISSUE TITLE
Pane orientation and editor type button icon states should be reversed

### ISSUE THREAD

**Issue by sprusr** [espruino/EspruinoWebIDE#165]
The button for toggling between vertical and horizontal pane orientation shows a vertical split to switch to horizontal, and a horizontal to switch to vertical. Likewise the button to switch to graphical editor shows the angled bracket "code" icon, and to switch to code shows a jigsaw icon.

It makes more sense for these to be the other way round, as the state is already reflected by what layout/type of editor is displayed.

I suppose this is also somewhat opinionated, and a fairly trivial issue. Thoughts?

**Comment by gfwilliams** [comment]
I'd be interested to see what others think.

When this was done initially I'm pretty sure this was discussed, and we came down on the side of what we have currently. I think the reasoning was that it seemed more obvious what the button did if it reflected the current state.

For example the 'connect' icon shows the 'disconnected' state by default - which I think is reasonable. But then you have to ask why all the other icons are the other way around :)

**Comment by sprusr** [comment]
@gfwilliams yes, the reason I opened an issue rather than submit a PR is for discussion 👍

It makes perfect sense for the connect/disconnect icon to be the way it is, I agree. But as you say, this shouldn't necessarily be the case for these other two buttons.

**Comment by gfwilliams** [comment]
@mattbrailsford did you have strong feelings about this? I'm veering towards @sprusr's suggestion.
