### ISSUE TITLE
bluetooth : missing the last piece of the puzzle

### ISSUE THREAD

**Issue by OwenBrotherwood** [espruino/EspruinoWebIDE#167]
I have created a EspruinoWebIDE from the github and am using npm start
Although espruino can see the device, I may be missing the last piece of the puzzle to get the npm start of EspruinoWebIDE to "see" the bluetooth connection.

espruino is global (npm install -g .) and works.
no obvious errors in npm install for EspruinoWebIDE 
running on .... Windows 10 :)

```
C:\Users\owen\source\repos\github\espruino>Espruino --list
Espruino Command-line Tool 0.0.30
-----------------------------------

PORTS:
  fb:a4:2f:9e:7c:5e (Espruino NRF52832DK)
  COM3 (Microsoft)
  COM5 (SEGGER)


```

**Comment by OwenBrotherwood** [comment]
Testing with http://www.espruino.com/Web+IDE#as-a-native-application and then come back with a dummies guide to create from github

**Comment by gfwilliams** [comment]
If you follow the http://www.espruino.com/Web+IDE link, you get a link to an installer for the Web IDE that should 'just work'.

When you install it yourself and try and `npm start` the IDE itself, you probably hit what's described here: https://github.com/espruino/EspruinoWebIDE#installing-from-npm

> If you're not seeing any options for devices to connect to, it might be because your nw.js and node versions don't match. If that's the case you need to manually rebuild all the 'native' modules.

So now you've got something working - what is actually the problem here? That it's connecting to the micro:bit but you can't write anything?

**Comment by OwenBrotherwood** [comment]
nRF52-DK: no problems
micro:bit is tracking on https://github.com/espruino/Espruino/issues/1040 

micro:bit is on hold until I can successfully build everything from source with focus on nRF52-DK and then puck.js when it comes.

I continue with the native modules: I have done this before, just need time to look thru the code.
NOTE: I can build espruino from source (no problems with native) so there is something I have to check in the EspruinoWebIDE to get sucess

> C:\Users\owen\source\repos\github\espruino>Espruino -p d7:af:86:be:70:29

I will have a result by the end of this week with possible PR for documentation on the process, otherwise I will make a call out as a last resort.

**Comment by gfwilliams** [comment]
So what's the problem here? Just that you connect on micro:bit but don't see the Espruino logo?

But it's still totally usable?

**Comment by OwenBrotherwood** [comment]
Let's forget micro:bit for the time being: nRF52-DK is working fine as is reference until I get a puck.js
