### ISSUE TITLE
Possible upstream issues with noble causing No compatible USB Bluetooth 4.0 device found!

### ISSUE THREAD

**Issue by OwenBrotherwood** [espruino/EspruinoWebIDE#168]
http://forum.espruino.com/comments/13473028/ for some background.
Possible problems with noble https://github.com/sandeepmistry/noble/issues/553

Installation: Windows 10 with Zadig giving No compatible USB Bluetooth 4.0 device found! with github clone (and in the IDE console and in downloaded Native)

![image](https://cloud.githubusercontent.com/assets/866122/22940257/9840c89c-f2e1-11e6-9b25-c0ff9b0e4c7c.png)

using C:\nwjs\nwjs-sdk-v0.20.1-win-x64 (there may be a need to debug ...)

```
git clone --recursive https://github.com/espruino/EspruinoWebI­DE.git
npm install
```

```

C:\source\repos\github\espruino\Espruino­WebIDE\node_modules\noble>node examples\advertisement-discovery.js
C:\source\repos\github\espruino\Espruino­WebIDE\node_modules\bluetooth-hci-socket­\lib\usb.js:70
    throw new Error('No compatible USB Bluetooth 4.0 device found!');
    ^
Error: No compatible USB Bluetooth 4.0 device found!
    at BluetoothHciSocket.bindUser (C:\source\repos\github\espruino\Espruin­oWebIDE\node_modules\bluetooth-hci-socke­t\lib\usb.js:70:11)
    at BluetoothHciSocket.bindRaw (C:\source\repos\github\espruino\Espruin­oWebIDE\node_modules\bluetooth-hci-socke­t\lib\usb.js:28:8)
    at Hci.init (C:\source\repos\github\espruino\Espruin­oWebIDE\node_modules\noble\lib\hci-socke­t\hci.js:101:35)
    at NobleBindings.init (C:\source\repos\github\espruino\Espruin­oWebIDE\node_modules\noble\lib\hci-socke­t\bindings.js:82:13)
    at new Noble (C:\source\repos\github\espruino\Espruin­oWebIDE\node_modules\noble\lib\noble.js:­50:18)
    at Object.<anonymous> (C:\source\repos\github\espruino\Espruin­oWebIDE\node_modules\noble\index.js:4:18­)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

```
```
C:\source\repos\github\espruino\EspruinoWebIDE>rmdir /S node_modules
C:\source\repos\github\espruino\EspruinoWebIDE>node install ..\..\sandeepmistry\node-bluetooth-hci-socket
C:\source\repos\github\espruino\EspruinoWebIDE>node install ..\..\sandeepmistry\nobel
npm install
```

```
C:\source\repos\github\espruino\EspruinoWebIDE\node_modules\noble>node examples\advertisement-discovery.js
peripheral discovered (bc1485e88e81 with address <bc:14:85:e8:8e:81, public>, connectable true, RSSI -62:
        hello my local name is:
                [TV] UE48J5515
        can I interest you in any of the following advertised services:
                []
        here is my manufacturer data:
                "7500420401018fbc1485e88e81be148564cf4024000000000000"

peripheral discovered (dff5a5ec431b with address <df:f5:a5:ec:43:1b, random>, connectable true, RSSI -45:
        hello my local name is:
                Puck.js 431b
        can I interest you in any of the following advertised services:
                ["6e400001b5a3f393e0a9e50e24dcca9e"]

```

Edit
EspruinoWebIDE log: going for EspruinoTools tests 
```
We have chrome.serial - not using 'serialport' module
'noble' module couldn't be loaded, no node.js Bluetooth Low Energy  Error: A dynamic link library (DLL) initialization routine failed. \\?

```

Edit

EspruinoTools does not "see" ble at the moment
```
C:\source\repos\github\espruino\EspruinoWebIDE>npm install -g EspruinoTools
C:\source\repos\github\espruino\EspruinoWebIDE>c:\Users\owen\AppData\Roaming\npm\espruino.cmd
C:\source\repos\github\espruino\EspruinoWebIDE>c:\Users\owen\AppData\Roaming\npm\espruino.cmd --list
Espruino Command-line Tool 0.0.30
-----------------------------------

PORTS:
  COM3 (Microsoft)
```
```

C:\source\repos\github\espruino\EspruinoWebIDE\EspruinoTools>rmdir /s node_modules
C:\source\repos\github\espruino\EspruinoWebIDE\EspruinoTools>npm install ..\..\..\sandeepmistry\node-bluetooth-hci-socket
C:\source\repos\github\espruino\EspruinoWebIDE\EspruinoTools>npm install ..\..\..\sandeepmistry\noble
C:\source\repos\github\espruino\EspruinoWebIDE\EspruinoTools>npm install
C:\source\repos\github\espruino\EspruinoWebIDE\EspruinoTools>node bin\espruino-cli.js --list
Espruino Command-line Tool 0.0.30
-----------------------------------

PORTS:
  COM3 (Microsoft)
  df:f5:a5:ec:43:1b (Puck.js 431b)

```

EspruinoWebIDE still giving same error: dive into nw.js ?????????????????????????????????????????????????
```
We have chrome.serial - not using 'serialport' module
'noble' module couldn't be loaded, no node.js Bluetooth Low Energy  Error: A dynamic link library (DLL) initialization routine failed. \\?
```

Edit:
My only point of reference at this time is http://docs.nwjs.io/en/latest/For%20Users/Debugging%20with%20DevTools/

Edit
Doesn't work: possible disablement enablement needed
> Open Developer Tools
> DevTools can be opened with keyboard shortcut F12 on Windows and Linux or ⌘+⌥+i on Mac.
 
Edit:
Guessing ...

```
  "window": {
    "title": "Espruino Native IDE",
    "toolbar": true,
    "frame": true,
    "show": true,
    "fullscreen": false,
    "width": 1024,
    "height": 600,
    "position": "center"
  },
  "//chromium-args": "--enable-web-bluetooth",
  "chromium-args": "--enable-logging=stderr --enable-web-bluetooth",
  "//2": "-------------------------------------------------------- NPM",
  
```

Edit:

```
[11696:14664:0214/192750.935:WARNING:push_messaging_service_factory.cc(30)] PushMessagingService could not be built because InstanceID is unexpectedly disabled
[11696:14664:0214/192751.537:INFO:CONSOLE(30)] "We have chrome.serial - not using 'serialport' module", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (30)
[11696:14664:0214/192751.862:INFO:CONSOLE(30)] "'noble' module couldn't be loaded, no node.js Bluetooth Low Energy
", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (30)
[11696:14664:0214/192751.922:INFO:CONSOLE(30)] "'winnus' module not found, no Windows Bluetooth Low Energy", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (30)

```

Edit:
debugger/console at last
`
C:\source\repos\github\espruino\EspruinoWebIDE>nw --remote-debugging-port=9222 .`

Edit:
![image](https://cloud.githubusercontent.com/assets/866122/22943239/0f5189a2-f2ed-11e6-8413-3d92c622e0ac.png)

---
---

OK: I now have a Windows 10 Zandig Installation with nw.js SDK and can debug under suggestions as to what to do.
ie: that is about as far as I go just now until I get some good idea as to what to do next
---
---

Edit:
OK: one doesn't learn anything by sitting around: diving into https://github.com/tessel/node-usb
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\source\\repos\\github\\nonolith\\node-usb\\src\\binding\\usb_bindings.node" "--module_name=usb_bindings" "--module_path=C:\\source\\repos\\github\\nonolith\\node-usb\\src\\binding"
gyp ERR! cwd C:\source\repos\github\nonolith\node-usb
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\source\repos\github\nonolith\node-usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path=C:\source\repos\github\nonolith\node-usb\src\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\source\repos\github\nonolith\node-usb\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\source\\repos\\github\\nonolith\\node-usb\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\source\repos\github\nonolith\node-usb
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\source\repos\github\nonolith\node-usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path=C:\source\repos\github\nonolith\node-usb\src\binding' (1)
```

---
And a lot of other lovly, lovly stuff that ended me here: https://github.com/tessel/node-usb/issues/109
---

**Comment by OwenBrotherwood** [comment]
Sandeep is kindly investigating https://github.com/sandeepmistry/noble/issues/553#issuecomment-280199110

In the meantime, I have to investigate winnus: I give a call out if stuch, otherwise I believe I know what I am doing :)

```
\C:\source\repos\github\espruino\EspruinoWebIDE\node_modules\usb\src\binding\usb_bindings.node
'winnus' module not found, no Windows Bluetooth Low Energy Error: error: 126\\?\C:\source\repos\github\espruino\EspruinoWebIDE\node_modules\winnus\build\Release\winnus.node
```

**Comment by OwenBrotherwood** [comment]
I will write an example for winnus to make something like https://github.com/sandeepmistry/noble/blob/master/examples/advertisement-discovery.js which has helped me ensure the stack under noble works
ie ensure that winnus is working correctly within it's dependancies

**Comment by gfwilliams** [comment]
Winnus is purely for Windows 10 BLE - so if you're trying to debug Windows 7 there is no need to look into it.

**Comment by OwenBrotherwood** [comment]
OK: Status on my Windows 7 VM is as below
I start enabling more debug's with access to nw debug via port and obtain more info.
I update this issue comment with progress and if stuck, a new comment as call out


SEARCHING... NO PORTS FOUND
```
We have chrome.serial - not using 'serialport' module
'noble' module couldn't be loaded, no node.js Bluetooth Low Energy  Error: Systemet kan ikke finde meddelelsesteksten for meddelelsesnummer 0x%1 i meddelelsesfilen for %2. \\?\C:\source\repos\github\espruino\EspruinoWebIDE\node_modules\usb\src\binding\usb_bindings.node
'winnus' module not found, no Windows Bluetooth Low Energy Error: error: 126\\?\C:\source\repos\github\espruino\EspruinoWebIDE\node_modules\winnus\build\Release\winnus.node
serial_audio: Audio Sample rate : 44100
serial_audio: Audio Serial Baud 9600 Bit time 4.59375
No navigator.bluetooth - Web Bluetooth not enabled
GET chrome.storage.sync = undefined
Initialising SettingsConsole
```

**Comment by OwenBrotherwood** [comment]
OK: 99.9% noble problem: when packaged in IDE (C:\source\repos\github\espruino\EspruinoWebIDE\node_modules\noble>node examples\advertisement-discovery.js works so NOT a problem with my testing environment at the moment)

The key to the problem is the catch for why noble is going bad:

`Error: Systemet kan ikke finde meddelelsesteksten for meddelelsesnummer 0x%1 i meddelelsesfilen for %2.
`

**Comment by OwenBrotherwood** [comment]
I have done many things to get this far: all with reasonable care.
The status now is that sometimes I get a prompt with EspruinoTools, sometimes not.

Do I downgrade puck.js or pull the lattest puck.js code?

After input, I go back to node module hell.

[onAndOff.txt](https://github.com/espruino/EspruinoWebIDE/files/779986/onAndOff.txt)

**Comment by gfwilliams** [comment]
Strange - not sure what to suggest. Stupid question - but is it close enough to the PC? It it's behind a wall or more than ~10m away it could be hard to connect to.

Have you tried the newest command-line tools from GitHub? Those can wait a little longer for a connection.

Also, you could use `setAdvertising` on your Puck when you do connect, and then really shorted the advertising interval - to 50ms or so - and see if that makes a difference?

I have a feeling that maybe some of the USB Bluetooth keys only listen on one channel (not all 3) which makes it very hard for them to connect

**Comment by OwenBrotherwood** [comment]
No question is too stupid :)
puck.js close to PC
EspruinoTools are from fresh clone 
I try and find how to setAdvertising. and edit this comment until next result/problem

**Comment by OwenBrotherwood** [comment]
Oops:
NOTE:
- scan allways give a puck.js. It is the connecting after the scan that gives problems

ie 
```

Found UART device: Puck.js 431b df:f5:a5:ec:43:1b
PORTS:
  df:f5:a5:ec:43:1b (Puck.js 431b)
Using first port, {"path":"df:f5:a5:ec:43:1b","description":"Puck.js 431b","
":"bluetooth"}
Connecting to 'df:f5:a5:ec:43:1b'
noble stopping scan
BT> Connecting
BT> ERROR Connecting
Unable to open device (connectionInfo=undefined)
Unable to connect!

```

And it is the failure of the connect after the scan that is "interesting"

**Comment by OwenBrotherwood** [comment]
My current plans:
- no more room on my laptop for development of Windows 7 (VM) and Windows 10
- saving Windows 7 VM as an Virtual Box archive to be used later
- wipe laptop (restoral point: I do this often and have data on the cloud)
- return to Windows 10 devel.: VM's are a pain
- setup nRF52-DK and puck.js to compare results of connection: if it works then I would have to find out if Windows 7 is really interesting for Espruino puck.js and Gordon to ensure time for Gordon to concentrate on Espruino puck.js and not on Windows 7 problems.

"I'll be back"

**Comment by OwenBrotherwood** [comment]
https://github.com/nodejs/node-gyp/issues/1116#issuecomment-280691889

> After a long trail, I have found the following:
> 
> node-usb, a very important piece of npm dependancy train may have troubles with 7.5.0
> nw.js is Chromium 56 + Node 7.5.0 and boy do I hate not using same node version
> but,
> "downgraded" to node 6.9.5 LTS and node-usb could compile and hope I don't get problems with nw.js when I get there.
> I will try out option 1 as soon as I have energy to remove VS2015 Community and start again.
>

**Comment by OwenBrotherwood** [comment]
Close: but no cigar :(

Notes:
- Windows 10
- nwjs-sdk-v0.20.2-win-x64
- nw-gyp rebuild --target=0.20.2 --arch=x64 # in binding.gyp directories
- noble from github
- node-bluetooth-hci-socket from github but not used in this scenario: windows 10

```
[4476:6924:0217/221807.087:INFO:CONSOLE(30)] ">>> Connecting...", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (30)
[4476:6924:0217/221807.089:INFO:CONSOLE(30)] "Set Slow Write = true", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (30)
[4476:6924:0217/221814.778:INFO:CONSOLE(40)] "Unable to open device (connectionInfo=undefined)", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (40)
[4476:6924:0217/221814.782:INFO:CONSOLE(40)] "[notify_error] Connection Failed.", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (40)
[4476:6924:0217/221814.802:INFO:CONSOLE(30)] ">>> Connection Failed.", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (30)
```

```

C:\source\repos\github\espruino\EspruinoWebIDE>nw . --enable-logging=stderr

C:\source\repos\github\espruino\EspruinoWebIDE>[4476:6924:0217/221730.968:WARNING:push_messaging_service_factory.cc(30)] PushMessagingService could not be built because InstanceID is unexpectedly disabled
[4476:6924:0217/221731.499:INFO:CONSOLE(30)] "We have chrome.serial - not using 'serialport' module", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (30)
[4476:6924:0217/221731.700:INFO:CONSOLE(30)] "'noble' module couldn't be loaded, no node.js Bluetooth Low Energy
", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (30)
[4476:6924:0217/221731.705:INFO:CONSOLE(30)] "Disable Web Bluetooth as we have Winnus instead", source: chrome-extension://bipaijaoackljocodhjdhecjbfoajehf/js/core/settingsConsole.js (30)

```

<img width="771" alt="puck with chromium 56 node 7 5 0 nw" src="https://cloud.githubusercontent.com/assets/866122/23083676/31dc7fee-f55f-11e6-9699-b06cbf01b612.png">

**Comment by OwenBrotherwood** [comment]
No comment required: I am ensuring I have a good base on Windows 10

```
C:\source\repos\github\espruino\winnus>node hello.js
[ { name: 'Puck.js 431b',
    address: 'df:f5:a5:ec:43:1b',
    path: '\\\\?\\bthledevice#{6e400001-b5a3-f393-e0a9-e50e24dcca9e}_dff5a5ec431b#8&2e011fae&0&000b#{6e400001-b5a3-f393-e0a9-e50e24dcca9e}' } ]
{ name: 'Puck.js 431b',
  address: 'df:f5:a5:ec:43:1b',
  path: '\\\\?\\bthledevice#{6e400001-b5a3-f393-e0a9-e50e24dcca9e}_dff5a5ec431b#8&2e011fae&0&000b#{6e400001-b5a3-f393-e0a9-e50e24dcca9e}' }
Connect
Error: BluetoothGATTSetDescriptorValue
    at Object.exports.connect (C:\source\repos\github\espruino\winnus\winnus.js:34:10)
    at Object.<anonymous> (C:\source\repos\github\espruino\winnus\hello.js:24:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)

```

I am not a full time programmer IRL: so this is cut and paste to give me context to test with.
There are probably inevitable mistakes and wrong assumptions: I'll get there

```
var winnus = require("./winnus");
var devices = null;
var device = null;
var errorCode = 0;

function connected(data){
  console.log("Got data "+JSON.stringify(data));  
}

errorCode++;
try {
  devices = winnus.getDevices();
  console.log(devices);
  device = devices[0];
  console.log(device);  
} catch (error) {
  console.error(error);
  process.exit(errorCode);  
}

errorCode++;
try {
  console.log("Connect");
  winnus.connect(device, function(data) {
    console.log("Got data "+JSON.stringify(data));
    process.exit(0);
  });  
} catch (error) {
  console.error(error);
  process.exit(errorCode);
}
winnus.write("Hello");

errorCode++;
setTimeout(function() {
  console.error("Timeout");
  try {
    winnus.disconnect();   
  } catch (error) {
    console.error(error);
  }
  process.exit(errorCode);
}, 1000);

```

Current release of nw.js dictates that the node v7.5.0 should be used, nw-gyp with nw.js and node-gyp for cmd line node (as far as I can see).
End game is a perfect EspruinoWebIDE from source for a future release of IDE where tests are primarily on Windows 10 with possible Windows 7 solution on request.
I doubt that chrome on Windows 10 get's to Connect to a Bluetooth device in the time frame that is perceived for the above.

> Windows 10 with Intel Wireless Bluetooth 7265	0x8087	0x0a2a
> nw.js v0.20.2
> Node v7.5.0
> Chromium 56.0.2924.87
> commit hash: f3d0ed8-0d73593-a2ef613-1f1f729

**Comment by OwenBrotherwood** [comment]
If the puck.js has a low battery, it can advertise but not be connected to.
I changed the battery and got a cigar for this one:

C:\source\repos\github\espruino\winnus>node hello.js
[ { name: 'Puck.js 431b',
    address: 'df:f5:a5:ec:43:1b',
    path: '\\\\?\\bthledevice#{6e400001-b5a3-f393-e0a9-e50e24dcca9e}_dff5a5ec431b#8&2e011fae&0&000b#{6e400001-b5a3-f393-e0a9-e50e24dcca9e}' } ]
{ name: 'Puck.js 431b',
  address: 'df:f5:a5:ec:43:1b',
  path: '\\\\?\\bthledevice#{6e400001-b5a3-f393-e0a9-e50e24dcca9e}_dff5a5ec431b#8&2e011fae&0&000b#{6e400001-b5a3-f393-e0a9-e50e24dcca9e}' }
Connect
Got data "Hello"

**Comment by OwenBrotherwood** [comment]
Building EspruinoWebIDE from github: Windows 10 and puck.js ONLY (USB support problems)
Download:
- node 7.5.0 
- nw.js (sdk is best) for same node version, currently 0.20.2 
- python 2.7.x (currently 13)
- http://landinghub.visualstudio.com/visual-cpp-build-tools or Community visual studion 2015 (expansion of doc needed)
- git clone --recursive https://github.com/espruino/EspruinoWebIDE.git
- IGNORE ALL usb errors
- EspruinoWebIDE\node_modules\winnus>nw-gyp rebuild --target=0.20.2

And smoke a cigar
PR on request for the doc README.md 

---
---

I regard this as good as I can now build for puck.js windows 10
BUT
BLOCKING issue for Windows 7 and usb with https://github.com/tessel/node-usb/issues/163

sandeep has a little refresh of npm as a problem for noble and bluetooth-hci-socket

---
---

**Comment by OwenBrotherwood** [comment]
Windows 10 
node 6.8.1 https://nodejs.org/download/release/v6.8.1/
nw.js https://nwjs.io/blog/v0.18.2/ (based on node 6.8.1)

All node_modules ok: EXCEPT for usb which is still a painful experience

```
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\owen\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:324:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\owen\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.18.6" "--arch=x64"
gyp ERR! cwd C:\source\repos\github\espruino\EspruinoWebIDE\node_modules\usb
gyp ERR! node -v v6.8.1
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
```

---

Method for nw-gyp: for all binding.gyp in node_modules do nw-gyp rebuild --target=0.18.6 --arch=x64
```
C:\source\repos\github\espruino\EspruinoWebIDE\node_modules>ls -R */binding.gyp
bluetooth-hci-socket/binding.gyp  serialport/binding.gyp  usb/binding.gyp  websocket/binding.gyp  winnus/binding.gyp

C:\source\repos\github\espruino\EspruinoWebIDE\node_modules>cd bluetooth-hci-socket

C:\source\repos\github\espruino\EspruinoWebIDE\node_modules\bluetooth-hci-socket>nw-gyp rebuild --target=0.18.6 --arch=x64
```

**Comment by gfwilliams** [comment]
When building the USB lib in Windows 10 I actually modified the windows header file - just seemed easier. After that the build works first time :)

I'm open to PRs that would trap certain errors and report them in a more helpful way...

**Comment by OwenBrotherwood** [comment]
https://github.com/sandeepmistry/noble/issues/553#issuecomment-281233648

Sandeep is releasing a  new npm on it's way for node- bluetooth-hci-socket which will make life easier for additional bluetooth adapters,

**Comment by gfwilliams** [comment]
Any news on this? Did the update fix the problems for you?

... or would it be possible to close this bug? I mean, on Windows 10 you shouldn't need `noble` anyway - and if winnus is reporting no device found then it's a driver issue rather than winnus' fault.
