### ISSUE TITLE
Espruino Web IDE requires system reboot for it to work again

### ISSUE THREAD

**Issue by psiphi75** [espruino/EspruinoWebIDE#169]
If am running the latest version of Espruino Web IDE on Linux (Ubuntu 16.10).  Steps to reproduce are:
1) Use Espruino Web IDE.  Close it.
2) flash the Espruino firmware on the board (an ESP32) via the command line
3) Start Espruino Web IDE again
4) Click the connect button.
5) Expect a connection.  But I get "disconnected".  When I look at the console in the Espruino Web IDE I get the following message:
```sh
>>> Connecting...
Set Slow Write = true
[object Object]
Connected [object Object]
ERROR: RECEIVE ERROR: {"connectionId":1,"error":"device_lost"}
Disconnect callback...
WARNING: [notify_warn] Disconnected
>>> Disconnected
ERROR: executeExpression called when not connected!
```

For Espruino Web IDE to work again I need to reboot my PC.

**Comment by gfwilliams** [comment]
Probably closing Chrome and re-opening it might help?

Although this sounds like it might be related to the ESP32 flasher? Normally this doesn't happen with the Web IDE on Linux - I use it every day and have never had to reboot to access devices.

**Comment by attilavago** [comment]
@gfwilliams , the exact same thing happened to me today on MacOS X 10.12.2 Besides the syntax error in the IDE code (which I reported and got fixed), it only worked once I rebooted my system. very odd... :/

**Comment by gfwilliams** [comment]
How are you using it? do you get the same log message?

 @psiphi75 is presumably using the Chrome Web App, and from the other 2 bugs you posted last night it seems you're trying to make it run under Node.js and NW.js instead? Did it work when you ran it as a Chrome Web App?

**Comment by psiphi75** [comment]
I'm using Chrome web app and experience the issue with the Chrome Web App.  I haven't posted any new bugs recently.

**Comment by gfwilliams** [comment]
Sorry - I meant to address that to @attilavago

@psiphi75 are you using Chrome Beta, or just normal Chrome?

**Comment by psiphi75** [comment]
Just normal Chrome.

**Comment by gfwilliams** [comment]
Have  you tried disconnecting and reconnecting the board? I've noticed that once or twice

**Comment by wilberforce** [comment]
I think this could be related to this issue:

https://github.com/espressif/esp-idf/issues/427

Opening and closing the port while data is getting sent... apparently a small delay before the re-open avoids the issue.

**Comment by gfwilliams** [comment]
Closing this - sounds a lot like it's the issue @wilberforce described and it seems there's not much the IDE can do.
