### ISSUE TITLE
Show Bluetooth device name in bottom right

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoWebIDE#171]
For Web Bluetooth it currently says `Web Bluetooth` - but it'd be much better if it showed the device name

**Comment by davidhay25** [comment]
Or upper left would be more obvious....

**Comment by gfwilliams** [comment]
Where did you have in mind? to the right of the connect icon?

There's already a connection type listed in the bottom right, so it's a relatively easy change to update that with the device name.
