### ISSUE TITLE
Service Worker fails to register on espruino.com/ide

### ISSUE THREAD

**Issue by jrstanley** [espruino/EspruinoWebIDE#178]
The Service Worker doesn't appear to load on https://www.espruino.com/ide/.

The console reports that https://www.espruino.com/ide/serviceworker.js isn't available, and when checking the URL directly in the browser I see that a 404 error is returned.

This does not impact https://espruino.github.io/EspruinoWebIDE/, which works as expected.

I'm unsure how espruino.com/ide is maintained/deployed, however I would suggest that either;

1. The serviceworker.js file is deployed (and any other related dependencies which could be missing and would cause the Service Worker registration to fail, i.e. those in the CACHED_RESOURCES array of serviceworker.js).

2. If there are other issues at play / complexities around updating or maintaining this on www.espruino.com/ide, we could exclude the espruino.com domain from Service Worker registration by editing the origin checks in index.html.

Thank you!

**Comment by gfwilliams** [comment]
Thanks - I'll look at this tomorrow - it could be that the file didn't get uploaded

**Comment by gfwilliams** [comment]
Fixed now - thanks!
