### ISSUE TITLE
Ctrl+S to save

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoWebIDE#180]
Currently files are saved on upload only. Having Ctrl-S to save would be much nicer.

**Comment by CWBudde** [comment]
While not directly related, is there already a shortcut to send/upload/deploy the code? If not, what function should get called? I can see the related code in send.js, but wouldn't it make sense to refactor it a bit to have one simple command called "send()" or "deployToBoard()" or similar?

Same, by the way, for saving. Then it could get added easily to the shortcut list.

**Comment by gfwilliams** [comment]
You could pull the contents of the `click` handler out into new function in `send.js` - might be easier?

As for saving, that's tricky - there's code in `file.js` but I believe the issue is that on a lot of platforms (the more web-based stuff) you currently need to open a 'file save' dialog for each save :( It may be that could be reimplemented though?  Perhaps once you have a handle to a file you can rewrite it without needing a new dialog?

I also just spotted a potential issue with auto-save - just described it at https://github.com/espruino/EspruinoWebIDE/issues/205
