### ISSUE TITLE
Cumulative notifications

### ISSUE THREAD

**Issue by jjok** [espruino/EspruinoWebIDE#181]
If I'm having trouble connecting, the first time I see the "Connection failed" notification. The second time I see two notifications. The third time; three. etc.

**Comment by gfwilliams** [comment]
Please can you let us know which device you're trying to connect to, which OS, Browser, and type of Web IDE (off espruino.com/ide, chrome app, windows installer, or NPM module)?

**Comment by jjok** [comment]
Oh, sorry.

* Puck JS
* Web IDE
* Chrome
* Linux/Ubuntu (16?)

**Comment by gfwilliams** [comment]
No problem - so you're talking `espruino.com/ide`? Also - which version of Chrome? And are you sure it's not Chromium - that's often a few releases behind and I know people have had issues with it.

Can you run `bluetoothd --version` and tell me what number it gives you? Also, have you ever managed to connect properly? Or it connected one or twice and then failed - I've had that happen on Linux and restarting the bluetooth service with `sudo /etc/init.d/bluetooth restart` generally fixes it.

**Comment by jjok** [comment]
The issue I was raising was that you get an extra notification every time, rather than that I was having trouble connecting.

I assumed it would just be something like forgetting to clear the notifications after they have been displayed.

Thanks for the tips on fixing the connection though.

**Comment by gfwilliams** [comment]
Ahh ok, I assumed it was both :)

I think I just discovered the problem with the multiple messages anyway, so I'll close this when I commit that fix?

**Comment by jjok** [comment]
Thanks. I'll try connecting again tonight, then maybe complain some more tomorrow :P

**Comment by gfwilliams** [comment]
Ok! :) Make sure you do a full reload of the page by holding Ctrl while you click reload - it tends to cache stuff pretty aggressively.
