### ISSUE TITLE
build error if libudev-dev is missing

### ISSUE THREAD

**Issue by werty1st** [espruino/EspruinoWebIDE#183]
i recommend to add

`sudo apt-get install libudev-dev`

to the instructions. Otherwise node-gyp complains about missing libudev.h

`pi@pizw:~/EspruinoHub2/EspruinoWebIDE $ npm install
> usb@1.3.1 install /home/pi/EspruinoHub2/EspruinoWebIDE/node_modules/usb
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-node-v57-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.3.1 and node@8.9.4 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/pi/EspruinoHub2/EspruinoWebIDE/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
`

**Comment by werty1st** [comment]
i wanted to post that issue on EspruinoHub and not here. sorry.

**Comment by gfwilliams** [comment]
Thanks - it looks like you're `npm install`ing EspruinoWebIDE though - all you need to do is `git clone` it for EspruinoHub - you don't need npm install at all.

Or are you finding you're having problems `npm install`ing even EspruinoHub?

**Comment by werty1st** [comment]
I tried to get the WebIDE running without the EspruinoHub.
Included with the Hub it always fails to start because i dont have a local mqtt and it doesn't take the mqtt settings from the config. it always tries to connect to a local mqtt.

after i forwarded the mqtt port to my remote mqtt it started but i never saw the Bluetooth device. Only the USB Serial Port.

i will create a separate issue for the mqtt settings problem.
i dont know why the bluetooth device is not found so i cant create an issue for that.

**Comment by gfwilliams** [comment]
Ok, thanks! Bluetooth could well be due to the need for `sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)`?
