### ISSUE TITLE
Latest WebIDE Broken

### ISSUE THREAD

**Issue by adatech** [espruino/EspruinoWebIDE#184]
i'm trying to use the latest WebIDE and it seems to be broken. Nothing displays in the console other than connected and disconnected. Also grabbed the latest in the repo and launched through nw and getting the same result.

**Comment by gfwilliams** [comment]
Can you try just using the normal ide chrome app?

Also, what device, what os?

If it's ESP8266 then 99.9% of the time it's because you didn't set the baud rate

**Comment by adatech** [comment]
I first tried the chrome app. It didn't work. I eve went in and raised the baud rate to 115000 and still no luck. So if the console doesn't respond it's typically not communicating properly, even though it says connected?

**Comment by adatech** [comment]
Oddly enough I just connected back up to try again and it started working. Thank you.

**Comment by gfwilliams** [comment]
So it was ESP8266? if you have any other issues please look/ask on the forum though  - you're far more likely to get useful advice  there
