### ISSUE TITLE
Require one module from another locally is broken

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoWebIDE#186]
It seems like there's something weird going on with project.js's handling of modules: http://forum.espruino.com/conversations/279130/#comment14110348

**Comment by nhamer** [comment]
- hello requires ["world"]
   Queueing world
[notify_info] No error. Minified 90 bytes to 81 bytes.
loadModule(world)
ERROR: Found module, but search took too long.
Espruino.Core.Utils.getURL: got HTTP status code 404 for https://www.espruino.com/modules/world.min.js
Espruino.Core.Utils.getURL: got HTTP status code 404 for https://www.espruino.com/modules/world.js
WARNING: [notify_warn] Module world not found

**Comment by nhamer** [comment]
Not a 100% repro - I was playing around with project directories, and it succeeded until exiting and restarting the IDE (Win10, native).

"search took too long" - project.js has a 50ms timeout on module load - may be as simple as bumping it.

**Comment by gfwilliams** [comment]
Thanks - just bumped it to 250ms and it works for me - although I disabled it if projects isn't enabled so it doesn't cause an extra delay for everyone.

That project code is pretty iffy - it seems to potentially call the callback function more than once or not at all, hence the timeout. I had a quick go at fixing it just now, but it ended up being too much of a nightmare - I think realistically it needs a bit of a rewrite.
