### ISSUE TITLE
Windows native: No affordances (close button) on browser window

### ISSUE THREAD

**Issue by nhamer** [espruino/EspruinoWebIDE#187]
Win10, espruino_ide_win64_0v68.6.exe

Open "Troubleshooting", see no navigation or other affordances in title bar - the only way to close the window is via the taskbar

Changing package.json@10 : frame: false to true fixes the bug, but then has both native and inline title bars for the main IDE windows.

remove class window--app from the main window, and kill the titlebar, and it's clean

**Comment by gfwilliams** [comment]
Thanks for letting us know! This is 'Troubleshooting' that appears in the 'Connect' menu when no devices appear? Or is it a link from somewhere else?

**Comment by nhamer** [comment]
No, from the help menu options - same for any browser window opened by nw

![troubleshooting](https://user-images.githubusercontent.com/24953871/36983689-dbe52ff4-2047-11e8-8d2c-f29dd0f1238c.png)

**Comment by gfwilliams** [comment]
Ahh - thanks. That's really annoying - it works great on ll other platforms.

Just sorted it, so it'll be in the next release which I'll try and push out soon.
