### ISSUE TITLE
Can't handle linked file in folder modules

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#192]
Web IDE versin 0.69.1 as Chrome extension on Mac OS X 

Linked a  file into modules folder and tried to upload, WebIDE cant find that linked file.

**Comment by MaBecker** [comment]
Is there a way to add this?

**Comment by gfwilliams** [comment]
I'm not aware of any way - it's dependent on the Chrome filesystem API: https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/js/plugins/project.js

If you used the command-line app (which now has an option to serve up the IDE over HTTP) then chances are it'd be fine.

And at some point Google will be killing their Web Apps, so even if that API could handle it, it might be a very short-term fix.

If you could find some other Web API that allowed filesystem access and which would work on the web-based version of the IDE (espruino.com/ide) then I'd be very happy to get it added though.

**Comment by MaBecker** [comment]
Thanks for your reply, so let's close this.
