### ISSUE TITLE
Variable rename in chrome extension

### ISSUE THREAD

**Issue by darkmoon32** [espruino/EspruinoWebIDE#193]
Hi, in extension version is not possible to rename variable. The dialog which is shown in web based version is not created and if I download the latest version from here and try to rename variable again, the error message **Uncaught Error: document.write() is not available in packaged apps.** is logged. By my understanding the problem should be that the compressed blockly is not allowed to create dialogs. Is there some work around? Perhaps using of uncompressed version of blockly or reimplementing the dialogs with their HTML equivalents?
Best regards,
Tomas

**Comment by gfwilliams** [comment]
Thanks for letting me know. That's frustrating - I was pretty sure this used to work with the older blockly version we'd been using before.

Unfortunately the issue isn't to do with whether it's compressed or not. `window.prompt` just isn't available for packaged apps. Looks like we'd have to reimplement a dialog in HTML and then write the function to `Blockly.prompt`. It's slightly confused by the fact we're using an iframe for Blockly, but I think that should still be ok.
