### ISSUE TITLE
Snippet is missing when using Unpacked Espruino IDE

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#198]
What am I missing ?

![bildschirmfoto 2018-11-17 um 05 04 06](https://user-images.githubusercontent.com/15932646/48656570-81ac2700-ea26-11e8-8e7c-6ffb0ab6853d.JPG)

**Comment by gfwilliams** [comment]
It doesn't appear by default - all you need to do is set up the project sandbox settings

**Comment by MaBecker** [comment]
Ups, to simple to figure out :)
