### ISSUE TITLE
Dismiss warnings

### ISSUE THREAD

**Issue by brendandower90** [espruino/EspruinoWebIDE#202]
Its very useful that Espruino gives me a warning to use "===" instead of "==", but sometimes I want to use the "==".
It would be good to be able to disable these warnings individually after acknowledging them.

**Comment by gfwilliams** [comment]
Thanks - it's a nice idea. I think it's probably too much effort to implement for each single error, however there was a request to be able to turn different classes of warnings on and off from settings, which might be a help?

The IDE itself uses CodeMirrror and JSHint (IIRC) so if you found an example of this somewhere then you should be able to add it in relatively easily.

**Comment by gfwilliams** [comment]
Now available as `Disable Code Hints`
