### ISSUE TITLE
Doesn't Connect to ESP8266MOD nor ESP32 on Windows 10

### ISSUE THREAD

**Issue by maxmedina05** [espruino/EspruinoWebIDE#207]
EspruinoWEBIDE doesn't detect ESP8266MOD nor ESP32 when running on Windows 10.  It tries to connect and then throws the following error:
![image](https://user-images.githubusercontent.com/6037236/63215085-9f2b3000-c121-11e9-87b7-ac73e2fc9964.png)

Windows detects both devices and can be read from Arduino Serial Monitor and/or Putty.

It works perfectly with the same devices on MACOS.

**Comment by MaBecker** [comment]
Set your baudrate to 115200?

**Comment by MaBecker** [comment]
![Bildschirmfoto 2019-08-18 um 03 09 43](https://user-images.githubusercontent.com/15932646/63218871-b55adf80-c165-11e9-99ac-99d27c9dacd4.jpg)

**Comment by maxmedina05** [comment]
I tried this already.

**Comment by maxmedina05** [comment]
I fixed this by updating the driver on the device manager.
