### ISSUE TITLE
Small IDE improvements

### ISSUE THREAD

**Issue by sebi5361** [espruino/EspruinoWebIDE#212]
Some ideas for small IDE improvements:
- When saving a file, `save as type` should be set to `*.js` by default (rather than `*.*`) allowing to enter a name for the file while omitting to write its extension.
- Similarly when opening a file,  `save as type` should be set to `*.js` to filter only the ad hoc files.
- When clicking on the upper left `Connect / Disconnect` icon, a pop-up window appears where you have to select a port (Web Bluetooth, Web USB, COMx). Such a pop-up window could be omitted if only one port type is available (E.g. Accessing directly the `"Espruino Web IDE" wants to pair` window when only `Web Bluetooth` is available).

**Comment by gfwilliams** [comment]
Hi,

Yes, those sound like good ideas. It's a bit limited in a web browser but it looks like it is possible to request a specific type of file: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Unique_file_type_specifiers

I'm not 100% sure about saving though.

In terms of connecting it's something i was wondering about myself - but my concern is that while it's an extra click it could be very confusing... What if you actually want to connect to a serial device but the only option available is Web Bluetooth and when you click connect it just opens the bluetooth window? I guess it could be a setting that defaults to 'off'?

**Comment by sebi5361** [comment]
Hi Gordon,
> Yes, those sound like good ideas. It's a bit limited in a web browser but it looks like it is possible to request a specific type of file.

That's a good news.

> What if you actually want to connect to a serial device but the only option available is Web Bluetooth and when you click connect it just opens the bluetooth window?

When using the online IDE, depending on, if only `Web Bluetooth` (`Web Serial` respectively), is ticked in the `Configuration/Communication` panel, the `www.espruino.com wants to pair` window (`www.espruino.com wants to connect to a serial port` window respectively) could be accessed directly without confusing the users, dont' you think? (When both options are ticked this intermediate window would appear still.)

When using the IDE Chrome app, `COMx`, `COMy` together with `Web Serial` can be displayed in the `Communication` window This is confusing. But as it is redundant, maybe a `Serial Connections` window with `COMx`, `COMy` could replace the `Web Serial` window. (This window would pop up directly or not depending on the options ticked in the `Configuration/Communication` panel.)

**Comment by gfwilliams** [comment]
IDE save/open file mime types are now supplied and the last opened filename is remembered.

I like the idea of omitting the 'web bluetooth' connect step, but right now I'm going to leave that as it's in all the documentation, and I'll certainly get complaints from new users if it changes :(
