### ISSUE TITLE
Emulator-Buttons with iOS  display as Ellipses

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#213]
Hi, 

just tested on iPhone and iPad with different browses, all with the same result.

![Bildschirmfoto 2019-12-01 um 12 48 10](https://user-images.githubusercontent.com/15932646/69913539-23879180-1439-11ea-9b74-63bbaacddbd2.jpg)

Any hints?

**Comment by gfwilliams** [comment]
Oh great. Thanks Apple.

I'm not sure - I bet there's something online about styling buttons with CSS to remove rounded edges though.

**Comment by MaBecker** [comment]
I guess boarder-radius: 0px might help

**Comment by MaBecker** [comment]
Look like -webkit-app-region: no-drag; is not supported on iPads and iPhones

macbook:

![Bildschirmfoto 2019-12-03 um 17 51 18](https://user-images.githubusercontent.com/15932646/70071530-c8e76480-15f5-11ea-8838-fe3b22fad2bb.jpg)

iPhone:

![Bildschirmfoto 2019-12-03 um 17 49 28](https://user-images.githubusercontent.com/15932646/70071532-c8e76480-15f5-11ea-833d-896ef7f30be2.jpg)

**Comment by MaBecker** [comment]
There are two errors:

jquery-1.11.0.js:9666 GET https://www.espruino.com/json/EMSCRIPTEN.json 404 (Not Found)

settingsConsole.js:40 getURL("https://www.espruino.com/json/EMSCRIPTEN.json") error : Not Found

**Comment by MaBecker** [comment]
Nice, latest online version has a fix.

![Bildschirmfoto 2020-01-21 um 23 25 39](https://user-images.githubusercontent.com/15932646/72848699-71847d00-3ca5-11ea-93c0-062b21549084.jpg)

**Comment by gfwilliams** [comment]
I've just fixed EMSCRIPTEN.json  - it'll appear next time I update the IDE
