### ISSUE TITLE
Button in "Settings - Project"  - does not work anymore

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#215]
![Bildschirmfoto 2020-01-26 um 09 03 14](https://user-images.githubusercontent.com/15932646/73132419-23f86f00-401b-11ea-9f34-d97bee23cc04.jpg)

Name of actual project does not show and a click on the button does not show local folders.

**Comment by MaBecker** [comment]
And save button does not respond.

![Bildschirmfoto 2020-01-26 um 13 48 45](https://user-images.githubusercontent.com/15932646/73135470-b6603900-4042-11ea-85d0-c7def06a34d6.jpg)

Hope this is not Mac OS X specific .....

**Comment by gfwilliams** [comment]
How are you using the Web IDE? Your own custom version from GitHub, or the one from the Chrome web store?

Because the Chrome Web Store version hasn't been updated in a few weeks so if it worked before and doesn't now, it's likely to be something else...

**Comment by MaBecker** [comment]
It is the GitHub version used in Chrome as unpacked version

Just cloned a fresh version

Save now works

**Comment by gfwilliams** [comment]
> Save now works

But project still doesn't work? Just tried on Linux and it's fine. Are you sure both EspruinoWebIDE and the EspruinoTools repo within it are up to date?

Since you have a dev version you can right click and choose 'inspect' to see the dev console. Maybe it'll show you some errors when you try and open the project dialog?

**Comment by MaBecker** [comment]
Well, I created a new clone with

git clone --recursive https://github.com/espruino/EspruinoWebIDE.git

**Comment by MaBecker** [comment]
Chrome Version 79.0.3945.130 (Offizieller Build) (64-Bit) on Mac Os X 10.15.2

**Output on Chrime console**

[Violation] Forced reflow while executing JavaScript took 44ms
settingsConsole.js:30 GET chrome.storage.local.OFFLINE_DATA = 0 bytes
blockly_espruino.js:25 window.onload ?lang=en&Enable=%7Cbluetooth%7Crobot%7C
extensions::platformApp:232 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
EventTarget.addEventListener @ extensions::platformApp:232
Blockly.bindEventWithChecks_ @ blockly_compressed.js:1665
Blockly.Flyout.init @ blockly_compressed.js:1556
Blockly.Toolbox.init @ blockly_compressed.js:1600
Blockly.init_ @ blockly_compressed.js:1653
Blockly.inject @ blockly_compressed.js:1645
window.onload @ blockly_espruino.js:52
settingsConsole.js:35 Section named Rollup was not added with Config.addSection
console.warn @ settingsConsole.js:35
getSections @ config.js:137
createSettingsWindow @ menuSettings.js:37
click @ menuSettings.js:28
settingsConsole.js:35 Unknown config type 'bool' for Config.SERIAL_FLOW_CONTROL

**Switching to PROJECT**

app.js:411 Uncaught TypeError: element.off is not a function
    at Object.remove (app.js:411)
    at showIcon (project.js:655)
    at showLocalFolder (project.js:222)
    at project.js:32

Jump to  (app.js:411)
      remove : function() {
        element.off(); // Remove all event handlers    <--- error
        element.remove();
      },

Hope this is helpful.

**Comment by gfwilliams** [comment]
Thanks! Yes, that is... I've been attempting to remove the reliance on jQuery for a lot of core stuff, but it looks like projects may do some strange stuff under the hood that pokes the internals :)

**Comment by gfwilliams** [comment]
Nope. Totally my fault - `.remove()` wasn't working in app.js :)

**Comment by MaBecker** [comment]
Thanks for fixing it.

**Comment by MaBecker** [comment]
just pulled and tested It, works.
