### ISSUE TITLE
 Ctrl+` shortcut malfunction with the Windows french keyboard

### ISSUE THREAD

**Issue by sebi5361** [espruino/EspruinoWebIDE#216]
To keep track of the bug discussed on the [forum](http://forum.espruino.com/conversations/342836/#comment15080486).

**Comment by sebi5361** [comment]
Will you have time to look at this issue?

For recall, shortcut Ctrl+` doesn't work with a french keyboard on Windows.

Indeed, with the french keyboard on Windows, `e.key` values are:
- "Dead" when pressing on the grave accent,
- **"`"** when pressing on the space bar preceded by the grave accent.

Thus the `key` value in the script is "Ctrl + Dead" when pressing on Ctrl+`.

The keyCode, `e.code` for the grave accent is "Backslash" on the MacBook french keyboard.

**Comment by gfwilliams** [comment]
Not for a while... I'm open to PRs though!

**Comment by sebi5361** [comment]
I remapped my keyboard to get a none dead ` key. Am closing this issue.
