### ISSUE TITLE
Add a keyboard shortcut for uploading code

### ISSUE THREAD

**Issue by urish** [espruino/EspruinoWebIDE#217]
@kerenk100 and I are preparing an "Espruino on Thingy:52" workshop, and we are really missing a keyboard shortcut to upload the code through the IDE. I looked for one in the documentation and the IDE source code, but couldn't find anything. Is it possible to add a keyboard shortcut for this?

I'm thinking Ctrl+U (or Cmd+U mac) could be used for this purpose (similar to Arduino).

**Comment by gfwilliams** [comment]
Sounds like a good plan - there's now a plugin for keyboard shortcuts, so adding this should be pretty straightforward

**Comment by urish** [comment]
Lovely. Do you want us to work on a PR? I see that the keyboard shortcuts file is [here](https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/js/plugins/keyShortcuts.js), where should we look for the code uploading functionality?

**Comment by gfwilliams** [comment]
A PR would be great - the code is at https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/js/core/send.js#L34

I wonder whether it's worth actually moving the code to keyShortcuts,js and then doing `Espruino.Plugins.KeyShortcuts.action("UPLOAD")` in `send.js`?
