### ISSUE TITLE
Syntax highlighting - additional styles

### ISSUE THREAD

**Issue by gisforgabriel** [espruino/EspruinoWebIDE#218]
The Web IDE is fantastic, so I am loathe to move back and forth between any other text editor. The only thing I'm missing is being able to work in my preferred syntax highlighting theme.

It looks like CodeMirror has a theme plugin for this - [CodeMirror (Source) Syntax Highlighting](https://ckeditor.com/cke4/addon/codemirror) ([demo](https://codemirror.net/demo/theme.html)) (if I understand correctly). Is it possible to integrate this into the Settings menu?

I'm afraid that I don't know/understand enough to give this a shot myself, but happy to test if it helps.

Cheers

**Comment by gfwilliams** [comment]
Hi,

I don't have time for this right now, but the code that runs the editor is here:

**Comment by gisforgabriel** [comment]
@gfwilliams No problem, I appreciate it's a low priority.

I'll have a look at cloning/forking with preferred style.

**Comment by gisforgabriel** [comment]
Many thanks @huntlyc 👍
