### ISSUE TITLE
No web serial in 0.73.0

### ISSUE THREAD

**Issue by opichals** [espruino/EspruinoWebIDE#219]
Setup
* MacBook Pro 13-inch, 2017, Two Thunderbolt 3 ports
* MacOS Mojave 10.14.6
* Chrome 79.0.3945.130 (Official Build) (64-bit)

When I use the 0.72.1 chrome app I see and can successfully connect

![ide-0721-connect](https://user-images.githubusercontent.com/140211/74178240-7fda0f00-4c3b-11ea-9b43-2e5e4c71c98e.png)

But with the www.espruino.com/ide (I did check the settings -> communications -> web serial checkbox) I don't have a serial option

![ide-0730-connect](https://user-images.githubusercontent.com/140211/74178265-89fc0d80-4c3b-11ea-9516-67083fee5f60.png)

**Comment by opichals** [comment]
However on an older machine:
* MacBook Pro (15-inch, Late 2011)
* MacOS 10.11.6
* Chrome Version 79.0.3945.130 (Official Build) (64-bit)

This appears and I can connect normally

![image](https://user-images.githubusercontent.com/140211/74179030-e4e23480-4c3c-11ea-80c9-932cbc52cceb.png)

**Comment by gfwilliams** [comment]
The actual serial ports being shown will only happen when using the Chrome App (chrome.serial is only available to to apps, and will be going away shortly).

I think `Web Serial` still has to be enabled with a flag? https://codelabs.developers.google.com/codelabs/web-serial/#2

Try enabling the `#enable-experimental-web-platform-features` flag in `chrome://flags`.

Otherwise please could you post the messages that appeared in the console?

**Comment by opichals** [comment]
> I think Web Serial still has to be enabled with a flag?

Oh! Thank you! Had that flag disabled on the newer machine.

It would help to put a note about that in the 'Settings' tab that one should check for the non-default browser settings (and possible which ones if the info would not get too long).

**Comment by gfwilliams** [comment]
Thanks - I'll add that. I just remembered there's an origin trial running too, so I'll add that

**Comment by opichals** [comment]
Or perhaps it should only pop-up when Web Serial is on in the settings and it doesn't detect it later on...

**Comment by gfwilliams** [comment]
Hopefully with the origin trial you won't actually even need to change the flag - it should 'just work' :)

I do wonder whether there's a nice way of troubleshooting though - maybe the connection window could have a 'status' link at the bottom, and when you click it you get a new window that shows you all the connection plugins and whether they are working or not?
