### ISSUE TITLE
Connect over TCP Address: No auth?

### ISSUE THREAD

**Issue by golmujik** [espruino/EspruinoWebIDE#221]
Any way to disable the Connect over TCP Address from esp8266 or add some auth to it. Because someone can update the code of my esp without my knowledge?

**Comment by MaBecker** [comment]
Hi, 

Yes there are two possible options:

* disable telnet via `require('TelnetServer').setOptions({mode:'off'});`
* or set a password `E.setPassword(password)`

For further opinions  join the [forum](http://forum.espruino.com)

**Comment by golmujik** [comment]
Thanks a lot for helping @MaBecker  :)

There would be a way to stop OTA firmware updates too?

1 more thing I can not get this script '''wiflash.sh''' mentioned here http://www.espruino.com/ESP8266_Flashing

**Comment by MaBecker** [comment]
> There would be a way to stop OTA firmware updates too?

There is new new pr  with `NO_FOTA=1 make ....` remove OTA which is not accepted yet ;-)

> I can not get this script '''wiflash.sh''' mentioned here

https://github.com/espruino/Espruino/blob/master/scripts/wiflash.sh

**Comment by golmujik** [comment]
The OTA firmware update is not a big issue compared to code update without a password.

Just to confirm you mean the pr with the request to remove OTA is not accepted yet right?
Because I don't have an issue with OTA without a password but I want to know that the OTA is still there?  I mean I can use the OTA feature to update my firmware?

**Comment by MaBecker** [comment]
> Just to confirm you mean the pr with the request to remove OTA is not accepted yet right?

https://github.com/espruino/Espruino/pull/1755

>  want to know that the OTA is still there? I mean I can use the OTA feature to update my firmware?

Yes this feature is only for boards like ESP01s or ESP8255 and for folks that build the firmware.

OK, this was the last response, use the forum.
