### ISSUE TITLE
Local module not found error

### ISSUE THREAD

**Issue by wolandec** [espruino/EspruinoWebIDE#222]
I selected a project folder and the modules folder was created there by IDE. I copied my scada.js folder into it.

Require module in my js file.
`const ScadaJs             = require("scada.js");`

And I've got a problem, that IDE search this module online instead of local folder.
`ERROR: getURL("https://www.espruino.com/modules/scada.js.js") error : Not Found
WARNING: [notify_warn] Module scada.js not found`

**Comment by MaBecker** [comment]
Hi, 

try it this way:  `const ScadaJs = require("scada");`

**Comment by wolandec** [comment]
> Hi,
> 
> try it this way: `const ScadaJs = require("scada");`

The folder name is scada.js

**Comment by MaBecker** [comment]
Espruino can only include files.

**Comment by wolandec** [comment]
> Espruino can only include files.

Got it, thank you!
