### ISSUE TITLE
Extending Blocky with new functionality.

### ISSUE THREAD

**Issue by davidbozo** [espruino/EspruinoWebIDE#223]
Hello, i was looking for a way to extend the IDE with new Blocky blocks. Like a RGB controller with a simple color picker. Is there any documentation about it? Or can someone give me some direction?

**Comment by gfwilliams** [comment]
Hi - sounds good. There's no documentation on it as far as I know, but the process is pretty easy:

* Create a new file in `blockly` with blocks in - https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/blockly/blockly_robot.js might be a good example. You have a function to define the block, and then a function to return the JS code for that block.
* Reference the file up the top of https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/blockly/blockly.html and the further down, create a category and list of blocks for it like https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/blockly/blockly.html#L381

How you actually make the blocks in blockly is all well documented on the blockly site, but I'd imagine you can get pretty far by just looking at the existing blocks and then checking the files in https://github.com/espruino/EspruinoWebIDE/tree/gh-pages/blockly to see how they're made.
