### ISSUE TITLE
Choosing image in Blockly mode always changes the first instance

### ISSUE THREAD

**Issue by yarons** [espruino/EspruinoWebIDE#227]
I tried adding some blocks to display several images one after the other.

So now I have several blocks with an option to select image, whenever I click the second block, the image on the first block changes, so I can't actually add several images one after the other using Blockly mode.
<img width="553" alt="Screen Shot 2020-04-08 at 12 56 35" src="https://user-images.githubusercontent.com/406826/78771251-8e714800-7998-11ea-9662-8a912e65672c.png">

**Comment by gfwilliams** [comment]
Sorry for the delay - just fixed this. It'll go live later today
