### ISSUE TITLE
Readme: recursive clone doesn't work 

### ISSUE THREAD

**Issue by enthusiasmus** [espruino/EspruinoWebIDE#228]
Hi guys,

I tried to clone this repository with the --recursive parameter (recommendation from the readme), but that doesn't work for me. One has to clone the repos separately. 

➜  projects git clone --recursive https://github.com/espruino/EspruinoWebIDE.git 
Klone nach 'EspruinoWebIDE' ...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 5422 (delta 2), reused 6 (delta 2), pack-reused 5405
Empfange Objekte: 100% (5422/5422), 8.19 MiB | 767.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (3673/3673), Fertig.
Submodul 'EspruinoTools' (https://github.com/espruino/EspruinoTools) für Pfad 'EspruinoTools' in die Konfiguration eingetragen.
Klone nach '/home/lukas/projects/EspruinoWebIDE/EspruinoTools' ...
remote: Enumerating objects: 180, done.        
remote: Counting objects: 100% (180/180), done.        
remote: Compressing objects: 100% (122/122), done.        
remote: Total 2407 (delta 106), reused 111 (delta 55), pack-reused 2227        
Empfange Objekte: 100% (2407/2407), 1.20 MiB | 822.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (1626/1626), Fertig.
fatal: Fehler am anderen Ende: upload-pack: not our ref 7daf6d87fdbf54a44e8a891b86c388fc40206ae9
fatal: Die Gegenseite hat unerwartet abgebrochen.
"fetch" in Submodul-Pfad 'EspruinoTools' ausgeführt, aber 7daf6d87fdbf54a44e8a891b86c388fc40206ae9 nicht
enthalten. Direktes Anfordern dieses Commits ist fehlgeschlagen.

Keep on the good work!
Best regards,
Lukas

**Comment by gfwilliams** [comment]
Ahh, sorry - I'd committed a link on a branch that I hadn't uploaded to GitHub

If you try now it'll be fixed :)
