### ISSUE TITLE
sort files in storage view alphabetically

### ISSUE THREAD

**Issue by ps-igel** [espruino/EspruinoWebIDE#232]
Can we make the list of files in storage ordered alphabetically? Right now it is in the order the files where created.

![image](https://user-images.githubusercontent.com/60899838/79671169-a337b200-81c8-11ea-987f-652b0009964b.png)

**Comment by gfwilliams** [comment]
Thanks - yes, I guess this makes more sense :) I'll try and combine it with a tweak to list files more memory-efficiently as well as it's been reported there are sometimes issues using the menu when an app is using a decent amount of RAM.
