### ISSUE TITLE
Pretokenisation error for numbers in exponent notation

### ISSUE THREAD

**Issue by ps-igel** [espruino/EspruinoWebIDE#233]
I played around with pretokenisation to save RAM by activating
**Pretokenise code before upload (BETA) in the WebIDE**.

There seems to be a bug with numbers in exponent notation:

`const r = 1E4;`
turns into 
```
>Uncaught ReferenceError: "E4" is not defined
 at line 2 col 9
const r=1 E4;
```

**Comment by gfwilliams** [comment]
This was fixed a few days ago but hasn't been pushed live yet.

I've just updated so if you refresh the Web IDE that should be fixed.
