### ISSUE TITLE
Timed out receiving file

### ISSUE THREAD

**Issue by FransM** [espruino/EspruinoWebIDE#234]
I uploaded a png image file of 100x118 pixels (attached)
![100px-Tux](https://user-images.githubusercontent.com/1893299/81047226-4885a200-8eba-11ea-884e-4a21c84f1f16.png)
. When uploading I selected RGB565.
After doing so I wanted to download the file back to my system to see how the file actually looks, but it failed with a "Timed out receiving file" message. The remainder of the file was shown in the terminal window.
I would expect that as long as data is received no timeout would occur.

**Comment by gfwilliams** [comment]
Hi - if you've got issues with the IDE, please could you post them into the IDE's GitHub repo?

**Comment by FransM** [comment]
Hi Gordon,
Thanks for transferring the issue.
I am using https://www.espruino.com/ide/
browser is chromium
Version 81.0.4044.122 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

Reason for trying to download is that I am rendering with
g.drawImage(require("Storage").read("tux.img")); 
This gives me an image at 0, 0. 
I was wondering if I could control the initial position by editing the img file (e.g. if the contents of an image file is similar to an Image Object).

Also downloading it could be useful if at some point I have to restore it (or if I want to release my app)

**Comment by gfwilliams** [comment]
Ok, thanks. I'll look into it.

> This gives me an image at 0, 0.

Did you just try `g.drawImage(require("Storage").read("tux.img"),x,y);` where x and y are the start locations?

**Comment by FransM** [comment]
> > This gives me an image at 0, 0.
> 
> Did you just try `g.drawImage(require("Storage").read("tux.img"),x,y);` where x and y are the start locations?

Not when I wrote it, but afterwards I did and that works for me. Haven't found a way to obtain the dimensions of an image (on disk) though. I'd like to have my image horizontally centered.
Basically I was thinking of a skinned clock where one could upload ones own skin

**Comment by gfwilliams** [comment]
The width and height are in the first and second byte. So:

```
var img = require("Storage").read("tux.img");
var w = img.charCodeAt(0);
var h = img.charCodeAt(1);
```

**Comment by ayusun** [comment]
This happened to me too. 
I was dumping the raw data onto a file, which I later wanted to analyse on PC, but got this time out :(
