### ISSUE TITLE
Web Serial speed is wrong.

### ISSUE THREAD

**Issue by Zibri** [espruino/EspruinoWebIDE#235]
The default speed when selecting Web Serial is wrong (9600)
It should be 115220.

Infact by changing the localStorage configuration I have put 115200 and the web ide works.

**Comment by MaBecker** [comment]
Only for ESP8266 and ESP32 you need to manually change to 115200

All original boards use 9600.

**Comment by gfwilliams** [comment]
Yeah, 9600 is actually correct for all official boards. Original reason being you can use a board as-is with HC-5/06 bluetooth or even serial over headphone jack.

There was some discussion about changing ESP8266/ESP32 to 9600 as it's a constant source of problems for users - and I have to artificially limit the transfer speed in the Web IDE anyway so as not to overflow input buffers.
