### ISSUE TITLE
IDE no longer able to connect. No service matching UUID found on device.

### ISSUE THREAD

**Issue by the-real-ed** [espruino/EspruinoWebIDE#244]
Hi,

First of all, thanks for your work on this software.

Please note this may not be an issue with the Espruino software, but something lower in the stack.

### The issue:

I was writing/pushing/testing code onto the BangleJS from the Espruino Web IDE when the connection dropped between the IDE and BangleJS.

I attempt to reconnect the Espruino Web IDE to the BangleJS, but I get a "Connection Failed" error in the console, and the following information in the Settings->Console:

> Connecting...
Set Slow Write = true
> Connecting to Bangle.js 42f5
BT>  Device Name:       Bangle.js 42f5
BT>  Device ID:         BYfxEVPBkeAIzXRROotySA==
> Connected to BLE
BT> Connected
BT> ERROR: NotFoundError: No Services matching UUID 6e400001-b5a3-f393-e0a9-e50e24dcca9e found in Device.
BT> Disconnected (gattserverdisconnected)
ERROR: [notify_error] Connection Failed.
> Connection Failed.

### Hardware/Software information
Espruino:
- Hardware: BangleJS
- Firmware version: 2v05 (I tried it with 2v08 too)

Development PC information:
- OS: Debian unstable/sid
- Kernel version: 5.9.0 (I tried 5.2.0 as an alternative)
- Bluetooth hardware: CSR 4.0 (according to dmesg, "CSR8510 A10")
- BlueZ version: 5.55
- Chromium version: 83.0.4103.116

### Things tried
- Tried to connect from the web browser IDE (failed)
- Tried with a different Linux kernel booted (5.2.0). Also unsuccessful
- Tried it with a different version of the BangleJS firmware (2v05 and 2v08 -- both failed)
- Tried to "clear" browser configuration (i.e. `rm -rf ~/.config/chromium ~/.cache/chromium`). Failed.
- I suspected it might be something deeper in the stack (e.g. bluetooth config being cached?), so I created a new Linux user on the same PC, and tried connecting, that failed too.
- Powering down/restarting the PC and BangleJS watch (power cycle the BT hardware). Unsuccessful.

### What worked:
- I tried from my other computer. The same software stack (i.e. Debian unstable). It worked. I could pair and push code to the same BangleJS.

### What changed recently:
- I've been using this setup weekly for the last 10 months (originally with other Espruino hardware), and it's been okay up until now.
- Latest changes include: upgrading firmware to 2v08, upgrading kernel to 5.9.0

### Debugging information
Based on my limited understanding of Bluetooth, it appears that the service UUID does exist (run on the PC experiencing issues):

> $ sudo bluetoothctl 
[bluetooth]# connect F3:CA:1F:3A:42:F5 
Attempting to connect to F3:CA:1F:3A:42:F5
[CHG] Device F3:CA:1F:3A:42:F5 Connected: yes
Connection successful
[CHG] Device F3:CA:1F:3A:42:F5 Connected: yes
Connection successful
[CHG] Device F3:CA:1F:3A:42:F5 UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Device F3:CA:1F:3A:42:F5 UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[NEW] Primary Service (Handle 0x1a7d)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000a
	00001801-0000-1000-8000-00805f9b34fb
	Generic Attribute Profile
[NEW] Secondary Service (Handle 0x1a7d)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b
	6e400001-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART Service
[NEW] Characteristic (Handle 0xd8ab)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000c
	6e400003-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART RX
[NEW] Descriptor (Handle 0x6da0)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000c/desc000e
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[NEW] Characteristic (Handle 0xd8ab)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000f
	6e400002-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART TX
[CHG] Device F3:CA:1F:3A:42:F5 UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Device F3:CA:1F:3A:42:F5 UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[CHG] Device F3:CA:1F:3A:42:F5 UUIDs: 6e400001-b5a3-f393-e0a9-e50e24dcca9e
[CHG] Device F3:CA:1F:3A:42:F5 ServicesResolved: yes

**Comment by gfwilliams** [comment]
Hmm - very strange. I did have something a bit similar on Linux myself once. Could you try going into the OS's bluetooth menu and if the device is listed there (it's a nightmare trying to find it) could you remove it?

![image](https://user-images.githubusercontent.com/754445/96702743-f6faa200-1389-11eb-9706-6e1978742d91.png)

Might also be worth seeing if some of the other methods of connecting work from the same computer? https://www.espruino.com/Interfacing#bluetooth-le

**Comment by the-real-ed** [comment]
Thanks for the quick reply.

I've removed the device, but that hasn't resolved the issue. FYI, the command (that should be available across all Linux DEs) appears to be: `sudo bluetoothctl` and then running `remove <Bluetooth Address>`.

As for the alternative methods. I'll give them a try in the next couple of days (or week) and report back.

**Comment by gfwilliams** [comment]
It sounds like you rebooted if you changed the module, but I've found on my XPS laptop occasionally I have to `modprobe -r btusb` and `modprobe btusb` to get it working again.

Hope you have some success - it's an odd problem for sure.

**Comment by the-real-ed** [comment]
I can confirm that I'm able to successfully connect/push code/receive data to/from the BangleJS using the bluepy method described here: https://www.espruino.com/Interfacing#python

**Comment by the-real-ed** [comment]
Thanks, I did try the kernel module remove/add as you suggested with no change in behaviour (still failing).

**Comment by gfwilliams** [comment]
Hmm - well this sounds like a Chrome issue. While I could try and ask some of the Web Bluetooth devs, Linux isn't a 'supported' platform :(

What about chrome://bluetooth-internals/#devices ? You may be able to inspect/forget the device there?

**Comment by the-real-ed** [comment]
I was able to successfully toggle the LED on the BangleJS by writing the hexadecimal `0x03104c45442e746f67676c6528293b0a10` (`LED.toggle();` with a newline, and terminal codes, etc) from within the Chromium browser using the link you provided.

Please see the attached screenshot.

![BangleJS Chromium BT Successful Write](https://user-images.githubusercontent.com/3036262/96834141-3362f680-148d-11eb-9cab-55f47fc3952e.png)

As per your suggestion, I "forgot" the device via the above link, but connection from the IDE was still unsuccessful.

**Comment by gfwilliams** [comment]
That's really odd - so Chrome knows about the service but doesn't seem to be reporting it correctly.

Just in case - have you tried Chrome, rather than Chromium? In my experience Chrome tends to be a few released ahead of Chromium.

**Comment by the-real-ed** [comment]
I tried with version 86.0.4240.111 (Official Build) (64-bit), and it too was unsuccessful.

However, I think I've found additional information. I'll post an update shortly.

**Comment by the-real-ed** [comment]
Comparing the `bluetoothctl` output between non-working PC and working PC (both using Chromium, and attempting to connect using the Espruino IDE).

I have a limited understanding of Bluetooth so this could be a red herring.

For the following, I launched bluetoothctl, then used the IDE inside Chromium to attempt to connect/push code to the BangleJS.

### Non-working
Note: the DELs before the NEWs.

```
$ sudo bluetoothctl 
Agent registered
[CHG] Controller 00:1A:7D:DA:71:13 Pairable: yes
[CHG] Controller 00:1A:7D:DA:71:13 Discovering: yes
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -80
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -72
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -78
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -72
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -73
[CHG] Device F3:CA:1F:3A:42:F5 RSSI is nil
[CHG] Controller 00:1A:7D:DA:71:13 Discovering: no
[CHG] Device F3:CA:1F:3A:42:F5 Connected: yes
[DEL] Descriptor (Handle 0x0000)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000c/desc000e
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[DEL] Characteristic (Handle 0x1600)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000c
	6e400003-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART RX
[DEL] Characteristic (Handle 0x1600)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000f
	6e400002-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART TX
[DEL] Secondary Service (Handle 0x9160)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b
	6e400001-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART Service
[CHG] Device F3:CA:1F:3A:42:F5 UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Device F3:CA:1F:3A:42:F5 UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[NEW] Secondary Service (Handle 0xea7d)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b
	6e400001-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART Service
[NEW] Characteristic (Handle 0xd8ab)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000c
	6e400003-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART RX
[NEW] Descriptor (Handle 0x4520)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000c/desc000e
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[NEW] Characteristic (Handle 0xd8ab)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000f
	6e400002-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART TX
```

### Working
```
$ sudo bluetoothctl
Agent registered
[CHG] Controller 48:D2:24:FF:EA:17 Pairable: yes
[CHG] Controller 48:D2:24:FF:EA:17 Discovering: yes
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -77
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -66
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -66
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -66
[CHG] Controller 48:D2:24:FF:EA:17 Discovering: no
[CHG] Device F3:CA:1F:3A:42:F5 RSSI is nil
[CHG] Controller 48:D2:24:FF:EA:17 Discovering: yes
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -66
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -66
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -66
[CHG] Device F3:CA:1F:3A:42:F5 RSSI: -66
[CHG] Controller 48:D2:24:FF:EA:17 Discovering: no
[CHG] Device F3:CA:1F:3A:42:F5 RSSI is nil
[CHG] Device F3:CA:1F:3A:42:F5 Connected: yes
[NEW] Primary Service (Handle 0x31bd)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000a
	00001801-0000-1000-8000-00805f9b34fb
	Generic Attribute Profile
[NEW] Primary Service (Handle 0x31bd)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b
	6e400001-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART Service
[NEW] Characteristic (Handle 0x957b)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000c
	6e400003-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART RX
[NEW] Descriptor (Handle 0x9040)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000c/desc000e
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[NEW] Characteristic (Handle 0x957b)
	/org/bluez/hci0/dev_F3_CA_1F_3A_42_F5/service000b/char000f
	6e400002-b5a3-f393-e0a9-e50e24dcca9e
	Nordic UART TX
[CHG] Device F3:CA:1F:3A:42:F5 ServicesResolved: yes
```

I'm wondering if the IDE handles these DEL events differently to the web browser, which leads to a difference in behaviour.

**Comment by gfwilliams** [comment]
Thanks - that log is interesting...

The thing is, the IDE uses Web Bluetooth, which isn't really dealing with anything at that low a level - it literally just calls `server.getPrimaryService("6e400001-b5a3-f393-e0a9-e50e24dcca9e")` and it seems that fails.

You could try using https://espruino.github.io/EspruinoWebIDE/ (which uses unpacked files) and then open the devtools, open https://espruino.github.io/EspruinoWebIDE/EspruinoTools/core/serial_web_bluetooth.js and the breakpoint line 145 and check it out.

You could also try https://wiki.makerdiary.com/web-device-cli/ - a different webpage that should also communicate with Espruino just fine via Web Bluetooth.

**Comment by the-real-ed** [comment]
Thanks, that's great info, I'll have a play with it this weekend and report back.

**Comment by the-real-ed** [comment]
I found the issue and solution. Thanks for all your help.

The short version is, remove the Bluetooth cache file for the controller/device combination as follows:
`sudo rm /var/lib/bluetooth/<Controller MAC>/cache/<Device MAC>`
For my combination of controller and BangleJS this was:
 `sudo rm /var/lib/bluetooth/00\:1A\:7D\:DA\:71\:13/cache/F3\:CA\:1F\:3A\:42\:F5` 
Note: depending on how the cache files are generated, it might be a good idea to stop the bluetooth service first via: 
`sudo systemctl stop bluetooth.service`
Then after deleting the cache file, start it back up with:
`sudo systemctl start bluetooth.service`

The longer version (for anybody that might stumble across this):
I stopped the Bluetooth service:
`sudo systemctl stop bluetooth.service`
And brought it up in debug mode:
`sudo bluetoothd -nd`
After attempting to connect to the device from the IDE, I noticed this in the debug log:
```
bluetoothd[132414]: src/device.c:gatt_debug() start: 0x0001, end: 0x0009, uuid: 00001800-0000-1000-8000-00805f9b34fb
bluetoothd[132414]: src/device.c:gatt_debug() start: 0x000a, end: 0x000a, uuid: 00001801-0000-1000-8000-00805f9b34fb
bluetoothd[132414]: src/device.c:gatt_debug() start: 0x000b, end: 0xffff, uuid: 6e400001-b5a3-f393-e0a9-e50e24dcca9e
bluetoothd[132414]: src/device.c:gatt_service_removed() start: 0x000b, end: 0xffff
```
Searching for "gatt_service_removed" I came across [a mailing list post that discusses "link keys"](https://www.spinics.net/lists/linux-bluetooth/msg66330.html).
Some more searching on ["bluez remove link key", I came across this post that informed me of /var/lib/bluetooth/](https://askubuntu.com/a/565977) (the path of the cache file explains why creating a new Linux user on the troublesome PC led to the same issue). After some backing up/deleting directories I figured out the solution above.

Again, thanks for your time. Much appreciated. All the best.

**Comment by gfwilliams** [comment]
Wow, thanks for the in-depth solution. That's great - hopefully it'll be some help if this comes up for anyone else.

>  creating a new Linux user on the troublesome PC led to the same issue

Was this the case for you as well as that poster?

**Comment by the-real-ed** [comment]
> Was this the case for you as well as that poster?
It was an issue for me, but I didn't read the links I posted thoroughly enough to determine if they tried/experienced the same thing :)
