### ISSUE TITLE
console.warn

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#246]
console.warn() is not available in Espruino. The WEBIDE does not complain, see attached screen shot.

![Bildschirmfoto 2020-11-18 um 17 20 42](https://user-images.githubusercontent.com/15932646/99557147-a2673880-29c2-11eb-8733-756c5b4d5522.jpg)

**Comment by MaBecker** [comment]
Should I close this issue?

**Comment by gfwilliams** [comment]
I think so, yes. The linter doesn't complain about unknown functions. If you call `foobar(123);` you don't get any warning.
