### ISSUE TITLE
Errors Loading UTF-8 formatted files via Chrome App

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#255]
External editor

![Bildschirmfoto 2021-09-02 um 11 08 14](https://user-images.githubusercontent.com/15932646/131827457-16b5aba9-4a98-42fb-b1bd-31d7d4a0c163.jpg)

WebIDE - Chrome App, v0.75.8

![Bildschirmfoto 2021-09-02 um 11 08 31](https://user-images.githubusercontent.com/15932646/131827469-ba6073d8-ca03-44c5-94f5-a9ac382cfb83.jpg)

WebIDE - https://www.espruino.com/ide/
![Bildschirmfoto 2021-09-02 um 12 11 51](https://user-images.githubusercontent.com/15932646/131827562-1ed36c50-c368-4784-beab-616158c38a85.jpg)

Sample text

[umlauts.js.txt](https://github.com/espruino/EspruinoWebIDE/files/7098165/umlauts.js.txt)

More infos: http://forum.espruino.com/comments/16077675/

Any idea how to handle this?

**Comment by MaBecker** [comment]
possible workaround .....

![Bildschirmfoto 2021-09-02 um 12 42 39](https://user-images.githubusercontent.com/15932646/131830686-f0588e7b-5c16-4707-9ac0-09adebfc7cba.jpg)

**Comment by MaBecker** [comment]
> Does it work for you when you copy/paste?

Yes copy paste works 

>  If you upload the attached (non-UTF8) file then it may actually work for you?

Yes it does

Just checking Sublime settings

```
	// The encoding to use when the encoding can't be determined automatically.
	// ASCII, UTF-8 and UTF-16 encodings will be automatically detected.
	"fallback_encoding": "Western (Windows 1252)",

	// Encoding used when saving new files, and files opened with an undefined
	// encoding (e.g., plain ascii files). If a file is opened with a specific
	// encoding (either detected or given explicitly), this setting will be
	// ignored, and the file will be saved with the encoding it was opened
	// with.
	"default_encoding": "UTF-8",
```

So saving the files as non-UTF-8 does the trick - Many thanks!

**Comment by gfwilliams** [comment]
Renamed - and lets leave this open. Ideally the IDE would be able to load UTF8 and convert it either way.

Lets ignore the Chrome App for now as at some point Google are still planning to kill it.

**Comment by gfwilliams** [comment]
Fixed now
