### ISSUE TITLE
How to filter devices when connection via WebIDE 

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#262]
In some cases there are more then 10 devices around and it is hard to  find the wanted one - so a ble device filter would be very helpful.

![Bildschirmfoto 2021-12-02 um 17 51 12](https://user-images.githubusercontent.com/15932646/144466741-4e95bed3-0078-445a-8960-a6e3d15d03fc.jpg)

**Comment by gfwilliams** [comment]
Well, there is a filter already based on the Nordic UART service - but I guess those are all your devices that are running Espruino.

That window is created by the Web Browser, so there's not much I can do there....

**Comment by MaBecker** [comment]
Ok, that’s what I thought, so let’s switch to the command line Version to update devices.

**Comment by gfwilliams** [comment]
In the `serial_webbluetooth.js` file you can where filters are applied to `requestDevice` - so you can remove the service check and then just filter based on name. I'm not sure it's something that makes sense to put into the main IDE though
