### ISSUE TITLE
Error in Screenshot Links in Readme File

### ISSUE THREAD

**Issue by tasnimzotder** [espruino/EspruinoWebIDE#264]
Screenshot links are returning `404: Not Found`

The links are -
  - [https://raw.github.com/espruino/EspruinoWebIDE/gh-pages/extras/screenshot.png](https://raw.github.com/espruino/EspruinoWebIDE/gh-pages/extras/screenshot.png)
  - [https://raw.github.com/espruino/EspruinoWebIDE/gh-pages/extras/screenshot2.png](https://raw.github.com/espruino/EspruinoWebIDE/gh-pages/extras/screenshot2.png)

The possible reason for error -
- there's no directory named `/gh-pages/extras` in the project directory.

![image](https://user-images.githubusercontent.com/44049528/151931863-1d9ff1af-e783-48da-8bf8-070c8febd7d7.png)

**Comment by gfwilliams** [comment]
Thanks! just fixed
