### ISSUE TITLE
Can't change UI theme

### ISSUE THREAD

**Issue by YSmetana** [espruino/EspruinoWebIDE#265]
Hello!

Web IDE 0.74.1 on macOS 12.1, Chrome Version 98.0.4758.80 (Official Build) (x86_64).

When I try to change theme under _Settings -> General -> JavaScript Editor Theme_ to any non-default
I see that the code window has no colors now (black on white).

**Expected:** code window has syntax highlight according to the selected theme.

Same issue with Chrome App, or IDE as web page in Chrome. No error messages in the Chrome web console.

Any advice? Thank you!

Info from the app _Settings -> Console_:

    We have chrome.serial - not using 'serialport' module
    UTF8 Library loaded successfully
    GET chrome.storage.sync = {"AUTO_SAVE_CODE":true,"BAUD_RATE":"115200","BLOCKLY_EXTENSIONS":"|bluetooth|robot|","BLOCKLY_LANGUAGE":"en","BLOCKLY_TO_JS":false,"BOARD_JSON_URL":"http://www.espruino.com/json","COMPILATION":true,"COMPILATION_URL":"https://www.espruino.com/service/compiler","DISABLE_CODE_HINTS":false,"ENABLE_Testing":false,"ENV_ON_CONNECT":true,"FONT_SIZE":"18","KEYMAP":"sublime","LOAD_STORAGE_FILE":2,"MINIFICATION_LEVEL":"","MINIFICATION_Mangle":true,"MODULE_AS_FUNCTION":true,"MODULE_EXTENSIONS":".min.js|.js","MODULE_MINIFICATION_LEVEL":"ESPRIMA","MODULE_PROXY_ENABLED":false,"MODULE_PROXY_PORT":"","MODULE_PROXY_URL":"","MODULE_URL":"https://www.espruino.com/modules","OFFLINE_DATA":"","OFFLINE_DATA_DOWNLOAD":"","OFFLINE_DATA_UPLOAD":"","OFFLINE_ENABLED":false,"PRETOKENISE":false,"RESET_BEFORE_SEND":true,"SAVE_ON_SEND":1,"SAVE_STORAGE_FILE":"","SERIAL_AUDIO":"0","SERIAL_FLOW_CONTROL":true,"SERIAL_IGNORE":"/dev/ttyS*|/dev/*.SOC|/dev/*.MALS","SERIAL_TCPIP":"192.168.1.139:23","SERIAL_THROTTLE_SEND":false,"SET_TIME_ON_WRITE":true,"SHOW_CODE_LINK_ICON":false,"SHOW_WEBCAM_ICON":0,"STORE_LINE_NUMBERS":true,"Sound_Error":"","Sound_Info":"","Sound_Success":"","Sound_Warning":"","Speak_Error":false,"Speak_Info":false,"Speak_Success":false,"Speak_Warning":false,"THEME":"default","UI_MODE":"Normal","WEBCAM_CONSTRAINTS":0,"WEB_BLUETOOTH":true,"WEB_SERIAL":true,"projectEntry":"B8A98DD05EBACB3C28EF0AC689B3A112:Downloads"}
    Initialising SettingsConsole
    Initialising Utils
    Initialising Config
    Initialising HTML
    Initialising Notifications
    Initialising Status
    Initialising App
    Initialising File
    Initialising Code
    Initialising Serial
      - Initialising Serial Chrome Serial
      - Initialising Serial Chrome Socket
      - Initialising Serial Web Audio
      - Initialising Serial Web Bluetooth
      - Initialising Serial Web Serial
    Serial> serial.getPorts exists - grab known devices
    Initialising Terminal
    Initialising CodeWriter
    Initialising Modules
    Initialising Env
    Initialising Flasher
    Initialising EditorBlockly
    Initialising EditorJavaScript
    Initialising Send
    Initialising MenuPortSelector
    Initialising MenuSettings
    Initialising MenuFlasher
    Initialising SettingsAbout
    Initialising SettingsFlasher
    Initialising BoardJSON
    Initialising VersionChecker
    Initialising Compiler
    Initialising Assembler
    Initialising GetGitHub
    Initialising Unicode
    Initialising Minify
    Initialising Pretokenise
    Initialising SaveOnSend
    Initialising SetTime
    Initialising Tutorial
    Initialising Webcam
    Initialising FontSize
    Initialising UiMode
    Initialising URLHandler
    Initialising CodeLink
    Initialising Project
    Initialising Testing
    Initialising Notification_Sound
    Initialising Tern
    Initialising Debugger
    Initialising Tour
    Initialising SettingsProfile
    Initialising HelpLinks
    Initialising Offline
    Initialising Storage
    Initialising KeyShortcuts
    Initialising CoreModules
    No code in storage.
    GET chrome.storage.local.OFFLINE_DATA = 0 bytes
    SET chrome.storage.sync = {   "AUTO_SAVE_CODE": true,   "BAUD_RATE": "115200",   "BLOCKLY_EXTENSIONS": "|bluetooth|robot|",   "BLOCKLY_LANGUAGE": "en",   "BLOCKLY_TO_JS": false,   "BOARD_JSON_URL": "http://www.espruino.com/json",   "COMPILATION": true,   "COMPILATION_URL": "https://www.espruino.com/service/compiler",   "DISABLE_CODE_HINTS": false,   "ENABLE_Testing": false,   "ENV_ON_CONNECT": true,   "FONT_SIZE": "18",   "KEYMAP": "sublime",   "LOAD_STORAGE_FILE": 2,   "MINIFICATION_LEVEL": "",   "MINIFICATION_Mangle": true,   "MODULE_AS_FUNCTION": true,   "MODULE_EXTENSIONS": ".min.js|.js",   "MODULE_MINIFICATION_LEVEL": "ESPRIMA",   "MODULE_PROXY_ENABLED": false,   "MODULE_PROXY_PORT": "",   "MODULE_PROXY_URL": "",   "MODULE_URL": "https://www.espruino.com/modules",   "OFFLINE_DATA": "",   "OFFLINE_DATA_DOWNLOAD": "",   "OFFLINE_DATA_UPLOAD": "",   "OFFLINE_ENABLED": false,   "PRETOKENISE": false,   "RESET_BEFORE_SEND": true,   "SAVE_ON_SEND": 1,   "SAVE_STORAGE_FILE": "",   "SERIAL_AUDIO": "0",   "SERIAL_FLOW_CONTROL": true,   "SERIAL_IGNORE": "/dev/ttyS*|/dev/*.SOC|/dev/*.MALS",   "SERIAL_TCPIP": "192.168.1.139:23",   "SERIAL_THROTTLE_SEND": false,   "SET_TIME_ON_WRITE": true,   "SHOW_CODE_LINK_ICON": false,   "SHOW_WEBCAM_ICON": 0,   "STORE_LINE_NUMBERS": true,   "Sound_Error": "",   "Sound_Info": "",   "Sound_Success": "",   "Sound_Warning": "",   "Speak_Error": false,   "Speak_Info": false,   "Speak_Success": false,   "Speak_Warning": false,   "THEME": "monokai",   "UI_MODE": "Normal",   "WEBCAM_CONSTRAINTS": 0,   "WEB_BLUETOOTH": true,   "WEB_SERIAL": true,   "projectEntry": "B8A98DD05EBACB3C28EF0AC689B3A112:Downloads" }
    Config.THEME => monokai

<img width="721" alt="image" src="https://user-images.githubusercontent.com/2463895/152759960-a620b2d2-a121-4358-b9f9-d36ba65bad70.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/2463895/152760360-39c6bcb8-3a52-407b-9ce8-6cecd694c659.png">

**Comment by gfwilliams** [comment]
Thanks - just fixed. Looks like the original contributor never checked that this worked on espruino.com/ide where all the CSS is rolled up into one file.

**Comment by gfwilliams** [comment]
It'll go live next time we push to the website

**Comment by YSmetana** [comment]
Thank you for such a fast reaction! :)
