### ISSUE TITLE
Decode JS interprets string contents as tokens

### ISSUE THREAD

**Issue by eiowlta** [espruino/EspruinoWebIDE#272]
I used the IDE to write the following code to a file.  It works as intended on the device
`g.reset().clear();
g.setFont('12x20').drawString("°",50,50);`

When I use the storage to view the file and click "Decode JS", I assume it interprets the byte inside the string as a pretokenized token because I end up with:
`g.reset().clear();
g.setFont('12x20').drawString("throw",50,50);`

**Comment by gfwilliams** [comment]
Ok, thanks! That's an odd one - I assumed we used the tokeniser, which should have avoided that

**Comment by gfwilliams** [comment]
pretty sure this is fixed now
