### ISSUE TITLE
"The state of the DFU process does not allow this operation"

### ISSUE THREAD

**Issue by SuperPupperDoggo** [espruino/EspruinoWebIDE#273]
I am getting this error when I try to update my bangle.js. The firmware is now corrupted saying BANK0 INVALID and I don't know what to do. This happens for any image I upload.

**Comment by gfwilliams** [comment]
Hi, what kind of computer are you trying to run the firmware update from? Have you tried doing the firmware update from any other types of computer (including a phone?)

Best bet at this point is to use the DFU/Nordic Connect Android or iOS app to update the firmware...

Info at:

http://www.espruino.com/Bangle.js#firmware-updates
http://www.espruino.com/Bangle.js2#firmware-updates

Normally on Bangle.js 2 we'd suggest just using the app loader firmware updater, but now it's at the point of being stuck in the bootloader, android/iOS is probably the best option.

**Comment by gfwilliams** [comment]
firmware updates got an overhaul recently so I think this is fixed
