### ISSUE TITLE
Not all of file name is visible under "Send to Espruino" icon

### ISSUE THREAD

**Issue by thyttan** [espruino/EspruinoWebIDE#277]
When working with multiple files for an app it's often not possible to see which of its corresponding files (app, boot, setting) is selected to be uploaded to, prompting me to reselect by pressing the small arrow to browse the storage.

One solution to this problem coud be to wrap the text to fit inside the slideable middle column.

E.g. quicklaunch:
![image](https://user-images.githubusercontent.com/97237430/224488957-c04613be-5ea0-412e-afa8-894ec1c6ac49.png)

My setup:
Chromium browser
Fedora Linux 37
1080p screen

**Comment by gfwilliams** [comment]
Thanks, although I wonder if even wrapping would show *all* the filename in that case unless it was willing to split words.

There's actually a plan to add multi-file support to the IDE at some point (it's something Google actually paid me some money towards) so I think at that point we might actually put tabs at the top of the screen in the blue area and the filename could be put in those

**Comment by thyttan** [comment]
>Thanks, although I wonder if even wrapping would show all the filename in that case unless it was willing to split words.

Splitting the string on dots and putting the new strings on separate lines with leading dots might be one way to go:

’’’
quicklaunch
.boot
.js
’’’

>There's actually a plan to add multi-file support to the IDE at some point (it's something Google actually paid me some money towards) so I think at that point we might actually put tabs at the top of the screen in the blue area and the filename could be put in those

At that point the problem will be solved then. 🙂
