### ISSUE TITLE
SlowWrite for espruino.com/ide/relay

### ISSUE THREAD

**Issue by d3nd3** [espruino/EspruinoWebIDE#278]
How much work is involved to enable the slow write setting in normal ide index.html into the relay/index.html? This feature will help greatly for me to connect. Same applies to bridge mode, since its very similar to relay.

Remember this: [https://github.com/espruino/BangleApps/issues/1834](https://github.com/espruino/BangleApps/issues/1834)

**Comment by gfwilliams** [comment]
Have you tried setting slow write on the Web IDE that is connecting? I believe that should work exactly the same as write requests aren't combined.

Also, just FYI but I'd recommend 'Remote Connection' now - https://www.espruino.com/ide then Connect, then the link at the bottom of the window. It should hopefully be more reliable.

**Comment by d3nd3** [comment]
I did as you described and it works, I assume it will work for relay too, but the the remote connection does look nice.  I have another issue with EspruinoHub not showing the bangle.js anymore, but not super important because I don't need to rely on that anymore.

**Comment by gfwilliams** [comment]
Great! Very odd about EspruinoHub not working though :(

I must admit I'm not actually running it here at the moment - now HomeAssistant has some BLE support built in it seems to integrate quite nicely. If only someone would write an Espruino plugin for HA :)
