### ISSUE TITLE
[BUG] Setting Vim keymap doesn't work

### ISSUE THREAD

**Issue by thyttan** [espruino/EspruinoWebIDE#280]
## The bug

Setting JavaScript Editor Keymap to "Vim" doesn't change the input mode.

## Reproduce:
1. Start Chromium Web Browser.
2. Open an incognito tab (to ensure cookies are default)
3. Navigate to https://espruino.github.io/EspruinoWebIDE
4. Do some text manipulation in right-hand side editor (Sublime mode should be active).
5. Change SETTINGS->GENERAL->JavaScript Editor Keymap to "Vim".
6. Exit settings and test keymap in right-hand side editor (notice it didn't change to Vim keymap).

**Comment by gfwilliams** [comment]
I think this is fixed with #282 now?
