### ISSUE TITLE
Editor: Undo in Emacs keymap can cause data loss

### ISSUE THREAD

**Issue by ticalc-travis** [espruino/EspruinoWebIDE#281]
I happened to be trying out the Emacs editor keymap in the IDE and hit a particularly nasty problem (reproducible in both my Firefox and Chromium browsers): Pressing Ctrl+Z (undo) immediately after loading the IDE page causes everything in that window to instantly vanish. Permanently. As far as I can tell, there is no “redo” option to bring it back. So if you hadn't saved the code anywhere in a while, you're out of luck.

In the default mode (Sublime, I think) the same thing happens, but you can press Ctrl+Shift+Z to redo and bring the text back, though it's not obvious. This does not work in the Emacs mode. (I don't know if the Vim mode is affected, as I couldn't switch to it; more on that problem in a moment.) Changing the keymap doesn't work without a page reload [whenever even that works—I'm getting to it :) ], which in turn saves the (empty) file in progress as well as destroys the Undo history, so it really does seem that you're hosed if you do this by accident.

On top of that, this seems to be difficult to recover from, as I'm finding it very difficult to actually change the keymap setting in the first place. 90% of the time I change it, the setting reverts to what it was before when I refresh the tab. I don't know exactly how I finally managed to change it back to Sublime, but it took numerous attempts before the changed option actually stuck.

So, in short, there are actually a few problems here that combine to produce a particularly ugly situation:

1. Emacs mode apparently lacks a Redo command (that I could find; the undo/redo behavior certainly doesn't work like in real Emacs)

2. For some reason upon load, the IDE always starts with an undo entry for “erase everything in the editor window”, even when the window did not actually start from a blank slate from the user's point of view

3. Changing keymaps does not work reliably. (Probably related: #280) The change does not take effect immediately, and the change usually gets reverted upon reload for some reason, making it very difficult to change in the first place. Then when you do manage to change it, it's very difficult to change back!

4. (Incidentally, I did not find Emacs mode particularly usable anyway. A lot of important key commands get overridden by browser shortcut keys and are therefore inaccessible. For instance, attempting to cut text with Ctrl+W just straight away kills the browser tab without any warning or confirmation.)

I can't seem to find the core implementation of undo/redo from a simple code search, so I don't know how “redo” could be added to the Emacs keymap, nor how we would prevent the first press of Undo erasing the editor window when nothing has actually changed yet.

**Comment by gfwilliams** [comment]
Personally, I'm tempted to remove the keymap option - this was added by someone and I'm not sure if they ever actually used it - as you say they keymaps often conflict with IDE or browser behaviour that I don't think can be changed, and I don't think they've ever managed to take effect until a reload of the IDE.

The undo issue is annoying though - I presume it's because changing the contents of codemirror itself creates an undo entry. There must be a way of setting the contents without doing that (or pulling out the top undo entry)

**Comment by ticalc-travis** [comment]
I wondered myself that keymaps might have been a bit ambitious for this. The key conflict issue has always been one of many awkward issues with web “apps”, given that historically the first web browsers weren't really designed with the concept in mind, and I never felt the web app concept has gotten a huge bit much more elegant even in modern times. But I guess that's a whole different philosophical discussion. :)

I did a quick Google for “codemirror don't add undo entry” and found [a post](https://discuss.codemirror.net/t/disable-ctrl-z-undo-for-the-very-first-change/4202/3) from someone with a similar issue to ours, and the answer said something about creating a state with the content already added, rather than adding it after the fact. That looks hopeful.

I notice there are some other settings for the editor, like color scheme, that also don't seem to want to be accepted when changed, even after reloading the page, so that looks like another thing to check on. Maybe some sort of settings saving callback that's not firing when it should? Color schemes do feel like a useful and desirable feature to me, particularly being able to set one with a dark background for more comfortable viewing at night.

**Comment by ticalc-travis** [comment]
Good news: It looks like I've figured out how to fix the editor options that weren't taking effect. It turns out that the code in the Settings panel has been broken for a while. It tries to reference a variable `codeMirror` that is undefined—clear to spot if you try to change settings with the browser console turned on. Judging from the commit history, my guess is that broke due to some refactoring over the years, especially adding support for multiple editor windows.

I notice an object `Espruino.Core.EditorJavaScript` defined toward the bottom of the source file which has a function `getEditors` which provides access to the `codeMirror` instances that the settings code was looking for. If this is the intended way to get at them, then [this experimental branch](https://github.com/espruino/EspruinoWebIDE/compare/master...ticalc-travis:EspruinoWebIDE:live-testing) on my personal fork looks like the solution. [Here's a live demo with the editor settings working.](https://ticalc-travis.github.io/EspruinoWebIDE/) This fixes the color themes, the keymap settings, and other editor settings, and best of all, changes to them work immediately without reloading the page! And there seem to be no more problems with them getting forgotten. I think the reason that was happening was simply the undefined error halting the function before settings could be written to browser local storage.

I'll see about trying to clean that up into a proper PR when I get a chance, and then maybe can try to look into the undo problem. There is one weird bug still where setting the editor theme to “default” in particular somehow makes the entire page's CSS go kablooey (but then it's fine after a reload).

**Comment by gfwilliams** [comment]
Ahh, thanks! I think that was probably my fault then.

That branch looks good, and yes, that was the idea for getEditors. However maybe it's best to remove the `getEditors = Espruino.Core.EditorJavaScript.getEditors;` and reference it directly each time - problem is if `getEditors` is ever changed such that it uses `this` in it, `this` never gets set if you call just `getEditors()` vs `Espruino.Core.EditorJavaScript.getEditors()` so it would break. The joys of JS :(

**Comment by ticalc-travis** [comment]
Ah, that's a good point; I'll make the change. I've been so spoiled by Python for so many years that JS takes some getting used to. Python `self` just automagically works in almost all cases; JS's `this` handling is rather annoying. Not to mention JS's over-forgiveness; so many of the bugs in JS I encounter are things that likely wouldn't have been overlooked if JS complained as often as Python does. :-) Oh well.

So here's PR #282. This should fix the editor settings plus the CSS problem when selecting the default editor theme that I mentioned earlier. I included a similar fix for the Beautify feature which I previously overlooked. It seems that's only accessible via Ctrl+B, though, which isn't available in all browsers. Maybe somewhere down the line it would be nice to have a dedicated editor menu or toolbar so users could see what the key shortcuts are and still be able to run options whose shortcuts are inaccessible for whatever reason.

This still doesn't fix the undo issue yet.

The only thing I don't like is that the settings panel obscures the editor when selecting themes. It would be better if you could see what the themes look like in the editor as you browse them, but that probably would require a bit of UI redesign.

**Comment by gfwilliams** [comment]
Thanks for this, that's great! We don't get many contributions for the Web IDE but it's the thing everyone ends up using, so stuff like this is amazingly helpful.

> The only thing I don't like is that the settings panel obscures the editor when selecting themes

I guess it might be possible to change `app.js` to allow popups to be dragged around/resized onscreen? Quite a lot of effort but I guess it might be useful elsewhere. Potentially we could come up with a section of HTML that had all the CSS classes for a bit of code, for example:

```
<span role="presentation" style="padding-right: 0.1px;"><span class="cm-keyword">function</span> <span class="cm-def">test</span>(<span class="cm-def">a</span>, <span class="cm-def">b</span>) { <span class="cm-variable">print</span>(<span class="cm-string-2">`Hello`</span>); }</span>
```

And then if that was in the config option description it could be coloured using the loaded CSS theme?

**Comment by ticalc-travis** [comment]
You mean like a preview in the settings panel showing sample code according to the theme selected? That could be helpful too and would probably be the quickest and easiest thing we could do. Perhaps if we ever did something like a toolbar for editor functions and such there could also be some of the options there or else give them their own (smaller) settings box, but that would be much more work.

Here is my first stab at fixing the issue with undo blanking the editor on page reload or in freshly-created editor tabs.
https://github.com/espruino/EspruinoWebIDE/compare/master...ticalc-travis:EspruinoWebIDE:fix-first-undo.rebased?expand=1

The codeMirror instance has a method `clearHistory` which can be used to reset the undo history to a fresh state after putting the initial code into the editor. The idea is to make sure we call that only when we know we've just created a new editor and placed initial code so that we don't accidentally destroy the user's change history. I wanted to make sure that operations like reloading a file from disk in an already open tab just push the change to the existing history like before, so that if the user reloads over unsaved edits by mistake they can still undo back to the previous version to recover them.

Currently I have the option implemented in `setFileEditorContents`, which needs to have the calling code pass information about whether there should be a blank history. Looking back I think it might be possible to just have everything that uses `setFileEditorContents` reset the history itself where needed, but I suppose that doing it in `setFileEditorContents` provides a sort of “standard” way (and there appears to be at least five or six different spots in the code that need to handle this case). The downside is that it has to take an optional extra argument, and then I had to also add an arg to `readFileContents` which calls `setFileEditorContents`, just so the higher-level code with the knowledge about whether it's a new tab can pass it all the way down the chain.

So far the implementation appears to work but could probably do with a bit more testing.

**Comment by ticalc-travis** [comment]
> So far the implementation appears to work but could probably do with a bit more testing.

Well, I've used this patch in the IDE fork I've been using for a while, and I guess it's as ready as it ever will be. It seems to work and I haven't encountered any obvious catastrophic issues. I've gone ahead and created PR #286 for it.

I think that would pretty much close this issue; this should take care of all the issues raised here that have practical solutions.

**Comment by gfwilliams** [comment]
Thanks! That looks great - just merged!
