### ISSUE TITLE
How could I load image from local Source Storage?

### ISSUE THREAD

**Issue by jiangtangaaaa** [espruino/EspruinoWebIDE#289]
Hello, I hope you can answer this question
First of all, I am a label-studio novice, and now I have encountered a problem, I am using a Windows system, I want to upload pictures from a local to label-studio, and I have set the settings to start, but I don't know if it is right
--- set LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
--- set LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=D:datamediapicture           
--- label-studio
My label-studio is installed using pip and the images are in the picture folder
and I always have problems setting Add Source Storage
<img width="559" alt="image" src="https://github.com/espruino/EspruinoWebIDE/assets/101043186/86e9df36-c6a0-4be9-92e8-2416d433ed94">

Another problem is that I currently have a model, I want to upload the annotated files and unlabeled images in JSON format in label-studio, and I want label-studio to do the verification, I don't know how to do this
I hope you can help me with this, thank you very much

**Comment by gfwilliams** [comment]
I'm pretty sure you have the wrong GitHub project - this is for the Esprtino Web IDE, not label-studio - maybe you needed https://github.com/HumanSignal/label-studio ?

**Comment by jiangtangaaaa** [comment]
Hello, thank you very much for helping me answer my question
My label-studio was installed using pip install in pycharm
It should... there should be no problem, I'm not sure either

**Comment by jiangtangaaaa** [comment]
> I'm pretty sure you have the wrong GitHub project - this is for the Esprtino Web IDE, not label-studio - maybe you needed https://github.com/HumanSignal/label-studio ?我很确定你有错误的 GitHub 项目 - 这是针对 Esprtino Web IDE，而不是 label-studio - 也许你需要 https://github.com/HumanSignal/label-studio？

Hello, thank you very much for helping me answer my question
My label-studio was installed using pip install in pycharm
It should... there should be no problem, I'm not sure either

**Comment by jiangtangaaaa** [comment]
> I'm pretty sure you have the wrong GitHub project - this is for the Esprtino Web IDE, not label-studio - maybe you needed https://github.com/HumanSignal/label-studio ?
I just downloaded the git link you provided, opened the project with pycharm, and entered the following commands, but the console prompted an error
<img width="1080" alt="image" src="https://github.com/espruino/EspruinoWebIDE/assets/101043186/3a5e6b02-cb82-46ed-9886-342fc29e11fe">

**Comment by jiangtangaaaa** [comment]
After reading everyone's responses, I have a few small questions, I hope you can help me
看完大家的回答后，我有几个小问题，希望大家能帮到我
I have a model generator, it generates a COCO format annotation file, I want to import the coco format annotation file in Label-studio to further verify and improve the accuracy of the model annotation, how to import the coco format json file into the project?
我有一个模型生成器，它生成一个COCO格式的标注文件，我想在Label-studio中导入coco格式的标注文件，以进一步验证和提高模型标注的准确性，如何将coco格式的json文件导入到项目中？
Oh yes, I'm using a Linux operating system, and LS is installed with pip
哦，是的，我使用的是 Linux 操作系统，并且 LS 是用 pip 安装的
