### ISSUE TITLE
How could I load image from local Source Storage?<label-studio>

### ISSUE THREAD

**Issue by jiangtangaaaa** [espruino/EspruinoWebIDE#290]
Hello, I hope you can answer this question
First of all, I am a label-studio novice, and now I have encountered a problem, I am using a Windows system, I want to upload pictures from a local to label-studio, and I have set the settings to start, but I don't know if it is right
--- set LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
--- set LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=D:datamediapicture
--- label-studio
My label-studio is installed using pip and the images are in the picture folder
and I always have problems setting Add Source Storage
 https://user-images.githubusercontent.com/101043186/281981089-86e9df36-c6a0-4be9-92e8-2416d433ed94.png

Another problem is that I currently have a model, I want to upload the annotated files and unlabeled images in JSON format in label-studio, and I want label-studio to do the verification, I don't know how to do this
I hope you can help me with this, thank you very much

**Comment by gfwilliams** [comment]
I'm pretty sure you have the wrong GitHub project - this is for the Esprtino Web IDE, not label-studio - maybe you needed https://github.com/HumanSignal/label-studio ?
