### ISSUE TITLE
E.compiledC() subtle change

### ISSUE THREAD

**Issue by d3nd3** [espruino/EspruinoWebIDE#291]
Recently, I noticed that `E.compiledC()` does not get detected correctly (refuses to be sent to compiler server) if the:
```
{
var c = E.compiledC(`your c code`);
}
```
exists within scope curly braces ( like we use in fast load optimization ).

This code used to work because I had used it in the past with compiled C. Now I must remove the curly braces.
The compiler.js plugin looks for "VariableDeclaration", but with the curly braces gets "BlockStatement".  Which code change caused this and is it intended?

**Comment by d3nd3** [comment]
Actually, I am not 100% sure if I could do it in the past.  

In retrospect I think I might have just not realized that this must be in global scope.

**Comment by gfwilliams** [comment]
Hi - yes, this has never worked. I forget whether there was some reason for not doing it initially or not, but I guess it could be expanded at some point to try and search through the syntax tree a bit more
