### ISSUE TITLE
!!! Web IDE bricking v2 devices with "Firmware update" button

### ISSUE THREAD

**Issue by grandrew** [espruino/EspruinoWebIDE#292]
Just clicked the glowing yellow button to update firmware and v2 watch immediately bricked

Probably requires immediate action to prevent mass-bricking

Scenario:

1. Disabled BT on android phone
2. BT device appeared in Chrome/Windows 11
3. Clicked Pair
4. Clicked firmware update
5. Followed instruction to hold button, release while indicator moving on watch screen
6. Clicked next button
7. ERROR on device screen & web (can't remember which)
8. Device screen says press button to reboot
9. Button pressed, bootloop with error BANK0 INVALID

Context:

Received device yesterday, brand new, installed a couple of apps, paired to both PC and android.

**Comment by grandrew** [comment]
web console screenshot

![image](https://github.com/espruino/EspruinoWebIDE/assets/243218/99408dc8-02b2-4dbb-971e-75330268eaad)

![image](https://github.com/espruino/EspruinoWebIDE/assets/243218/10aad504-941c-4304-9759-d19a748f3ead)


```
Loading https://www.espruino.com/json/BANGLEJS2.json
index.js:92945 Board JSON loaded
blockly_espruino.js:114 Blockly.setBoardJSON  Object
index.js:92945 Firmware >1.43 supports faster writes over USB
index.js:92945 Set Slow Write = false ('Throttle Send'='Auto')
index.js:92945 FIRMWARE: Current 2v19, Available 2v20
index.js:92945 New Firmware 2v20 available
index.js:92945 [notify_info] New Firmware available (2.19 installed, 2v20 available)
index.js:92945 Device found {"portName":"Bangle.js c684"}
index.js:92945 [success] Connected to Web Bluetooth, Bangle.js c684
index.js:92945 >>> Connected to Web Bluetooth, Bangle.js c684
index.js:92945 Downloading https://www.espruino.com/binaries/espruino_2v20_banglejs2.zip
index.js:92945 >>> Downloading binary...
index.js:92945 >>> Done.
index.js:92945 BT> Disconnected (gattserverdisconnected)
index.js:92945 Disconnect callback... {"port":"Web Bluetooth","portName":"Bangle.js c684"}
index.js:92950 [notify_warn] Disconnected from Web Bluetooth, Bangle.js c684
(anonymous) @ index.js:92950
index.js:92945 >>> Disconnected from Web Bluetooth, Bangle.js c684
index.js:92945 stepFlashNordicDFU:  Object
index.js:92945 [success] Initialising...
2index.js:92945 >>> Initialising...
index.js:92945 connected to gatt server
index.js:92945 found DFU service
index.js:92945 found 2 characteristic(s)
index.js:92945 [success] Updating application: espruino_2v20_banglejs2_app.bin...
2index.js:92945 >>> Updating application: espruino_2v20_banglejs2_app.bin...
index.js:92945 connected to gatt server
index.js:92945 found DFU service
index.js:92945 found 2 characteristic(s)
index.js:92945 found packet characteristic
index.js:92945 found control characteristic
index.js:92945 enabled control notifications
index.js:92945 transferring init
index.js:92945 >>> Uploading...
index.js:92945 crc32 not found, skipping CRC check
index.js:92945 written 146 bytes
index.js:92945 transfer complete
index.js:92945 transferring firmware
index.js:92945 crc32 not found, skipping CRC check
index.js:92945 written 1900 bytes
index.js:92945 notify: Error: The state of the DFU process does not allow this operation
```

**Comment by gfwilliams** [comment]
So it's a Bangle.js 2?

Sorry this happened - it might be an issue with the Web IDE's DFU implementation on Windows. Usually it works but it seems sometimes on some platforms it doesn't.

Usually we try and ask people to update with the App Loader website, which works in a different way and is a bit safer: https://www.espruino.com/Bangle.js2#firmware-updates

**But all is not lost - the Bangle isn't bricked**. Just hold the button down as before to reboot and release as the `===` go across the screen, and you'll still get the bootloader. Then follow the instructions at https://www.espruino.com/Firmware+Update#nrf52 - ideally using the `DFU` app on a phone.

**Comment by grandrew** [comment]
Thank you very much for quick response! I'm currently looking into android method, as web IDE consistently can not pass the "DFU state" fail stage. I'm on MTK BT chipset, Lenovo Legion GO, Windows 11 insider beta 23H2 22635.2921

**Comment by gfwilliams** [comment]
Thanks - I'll have another look at this tomorrow and see if I can reproduce it on any computer I have here. I guess worst case I'll have to put up a big warning in the IDE for Windows users.

**Comment by gfwilliams** [comment]
Glad it's sorted - for starters I'll make sure the IDE attempts to direct Bangle.js 2 users to the app loader, but I'll look into what I can do to fix this too.

Just tested here and:

* Dell XPS 13 (older variant) works fine on Windows 10
* Lenovo Ideapad 5 Pro **fails** on Windows 11

At least I can reliably reproduce now - previously every PC I tried here worked fine but the Lenovo is a reasonably new purchase.
