### ISSUE TITLE
Web IDE error message on static class variables

### ISSUE THREAD

**Issue by AkosLukacs** [espruino/EspruinoWebIDE#298]
![image](https://github.com/espruino/EspruinoWebIDE/assets/844331/1af61545-4bf9-4bea-9f72-4c014ca5b65a)

But it does work on `VERSION: "2v22.39"` Espruino Wifi.

```
>Foo.TEST
=5
>
>
>new Foo()
But does it work? true
=Foo: {  }
>
```

**Comment by gfwilliams** [comment]
As you reported on https://forum.espruino.com/conversations/397119/#comment17425166 as well?

**Comment by AkosLukacs** [comment]
Yes, just it's not buried in the forum thread.
