### ISSUE TITLE
Re-implement popup close callback

### ISSUE THREAD

**Issue by mattbrailsford** [espruino/EspruinoWebIDE#44]
@gordon I notice that we both implemented the constant port checker script and implemented popup closing to kill the interval, but I think your implementation was better (I do a dirty replacement of the close method rather than using an onClose callback).

I think for the sake of some nicer code we should re-implement your method.

**Comment by gfwilliams** [comment]
Hmm. Old now - I think this is probably sorted (pretty sure there is a close callback now)
