### ISSUE TITLE
Give more context when requiring a connection

### ISSUE THREAD

**Issue by mattbrailsford** [espruino/EspruinoWebIDE#50]
Hey Gordon,

You mentioned you added the "ensureConnection" method which I think is a cool idea, but I might be tempted to still show a popup message. 

For example, if you click on "tutorial" and you aren't connected, it shows the port picker with no explanation as to why, so this could confuse the end user.

It might be worth showing a notification that says "Please connect first" or something.

Also, does the ensureConnection have a callback? such that when you have connected, the thing you tried to access will automatically trigger once you have connected? rather than needing to click the button again.

Matt

**Comment by gfwilliams** [comment]
Closing this one - apart from this issue nobody has ever complained about it
