### ISSUE TITLE
Git based code libraries / snippets

### ISSUE THREAD

**Issue by mattbrailsford** [espruino/EspruinoWebIDE#55]
Something I've seen in other software, but I think could be really cool for the Web IDE is to create a git repo of code libraries that can be accessed from the web IDE.

I think in the old UI you had a way to load some code snippets from the web, but I think this was just a repo on your server. If we can use a git repo instead (which all the API's are there, I've done it in a node-webkit project) it'll make it much easier to distribute updates and let other people contribute "Want a code snippet / library in the IDE, just send a pull request".

This could even be what is used when you do require(''), where the name could relate to a branch / folder in the repo.

**Comment by gfwilliams** [comment]
Closing this as it seems to work well - and we have https://github.com/espruino/EspruinoWebIDE/issues/60 for improvements
