### ISSUE TITLE
Terminal code completion

### ISSUE THREAD

**Issue by mattbrailsford** [espruino/EspruinoWebIDE#56]
Have the terminal know a list of supported commands, then when typing, if you hit tab, lookup the best match and auto complete for the user.

If multiple items match, auto complete up to the point the matches diverge (ie, if you type d+TAB, and supported commands are digitalWrite, digitalRead, auto complete the word "digital")

**Comment by gfwilliams** [comment]
Sorted now. Espruino does code complete, and the RHS is done by codemirror/tern
